// Generated by scripts/build-team-plan.mjs. Do not edit.
// Original prompts informed by the sources and tradeoffs in docs/team-examples.md.
const protocol = `WORKING AGREEMENT
Read the task briefing, repository instructions, tt agents, and tt inbox --unread --mark-read before acting. When a teammate sends you an ASSIGN, REQUEST, REVIEW or QUESTION, run tt ack SEQ before you start: it is not a board post, and the hub refuses your other posts while work addressed to you stays unacknowledged. The owner's actual objective and constraints override this template. If the repository, target environment, or desired outcome is missing, ask one precise question on the board and mark tt event needs_input with that question. Never invent a task from the example's name.

Use directed tt post --to NAME messages for assignments, findings, and review requests. When you supersede your own open request, run tt withdraw SEQ --reason TEXT so it stops obliging its recipient. Reply to a human with tt post --reply-to SEQ, without --to. Check the inbox at meaningful checkpoints and before finishing. Confirm a post succeeded before claiming delivery. Do not reply to a teammate's receipt or thanks. If a teammate has not registered yet, post the handoff on the board, check the roster again at your next checkpoint, and address the teammate when present.

State each handoff's objective, owned files or artifact, acceptance checks, dependencies, and definition of done. Before editing, inspect the working tree and agree on file ownership. Use isolated worktrees for overlapping changes. A remote machine does not imply a shared checkout: identify host, absolute path, branch and commit in handoffs. Never overwrite another member's work. Read-only reviewers remain read-only unless explicitly reassigned.

While waiting, do useful independent inspection within your role. When none remains, send the precise dependency, mark your turn done with a waiting explanation, and end the turn; a later directed message can resume you. Do not busy-poll, repeatedly ask the owner, or declare the whole task complete. Only spawn helpers for a concrete independent assignment when task settings permit it; honor the shared Max new agents allowance. No recursive delegation for its own sake. Each implementation worker session is dedicated to exactly one bug or feature; use a fresh agent session and context for a new item. After the orchestrator accepts your final handoff, verifies dependencies are resolved, and releases you, use tt close and finish quietly. Orchestrators close completed workers and helpers only after acceptance. Before closeout, inventory useful long-lived services descended from the worker's tmux session; hand them off or detach and reverify them if they must remain available. Use tt retire NAME only for intentional temporary retention of the same item context, and tt resume NAME before assigning more same-item work. For a terminal item, the item lead may run tt close --team after all team-held and team-sent obligations are closed; it closes item workers before the lead, clears the project orchestrator and preserves the database handler. The owner may use tt close --team --task ID. Keep the orchestrator and active database handler available while the project remains open.

Report evidence, not confidence alone: commands and outcomes, file/line or commit references, source links where applicable, and unresolved limitations. Keep routine board messages short and put detailed artifacts in a named file when useful. A reviewer disagreement gets one evidence-based correction/review cycle, then the lead decides or asks the owner if a real requirement is ambiguous. Stop when the acceptance checks pass; do not create extra work to keep agents occupied.`;
const member = (name, role, model, prompt, options = {}) => ({
  name,
  role,
  model,
  runtime: options.runtime || "codex",
  reasoning: options.reasoning || "",
  serverId: "",
  run: options.runtime || "codex",
  cwd: "",
  prompt:
    protocol +
    (options.format ? "\n\n" + messageFormat : "") +
    "\n\nYOUR ROLE\n" +
    prompt,
});
// Board message format for teams written against docs/message-broker.md.
// Phase 1: tt send validates typed posts; free text is still accepted.
const messageFormat = `BOARD MESSAGE FORMAT
Post with tt send, which checks the message before it reaches the board. Example: tt send --kind result --to lead --subject "Tests pass for the empty recipient check" --outcome done --status a1=pass --evidence "e1: go test ./cmd/tt -> ok" --ref commit=abc1234. Run tt send --help for every field. KIND is assign, request, review, question, result, answer, block, decline, finding or notice. Use NOTICE to tell someone to wait or share status. Use BLOCK only when you yourself are blocked; address it to whoever can unblock you, state what you need, and give the condition for resuming. The subject is plain English, at most 120 characters, with no IDs, hashes or paths; IDs go only in --ref. assign needs --objective, --owns and --acceptance a1=…; review needs --candidate, --scope and --acceptance; result needs --outcome, --status per criterion and --evidence; question asks exactly one --question; block needs --reason, --needs and --resume-when. Keep messages under about 2 KB; put longer material in a file and cite its path with --ref or --attachment. Never split content across posts. Do not post acknowledgement messages on the board; acknowledge with tt ack SEQ, then answer an assign, request or review with its result, a block, a decline with a reason, or one question. If this host's tt has no send command, post the same fields as text with tt post: first line KIND: subject, then one Field: value line each.`;
// Planned delivery targets a Claude Opus 5.5 (medium) lead. Until the lead can
// be woken automatically (docs/message-broker.md) it ships with Astra; swap it
// in Agents when ready. GPT-6 Sol and Luna require codex-cli 0.156.1 or later.
// GPT-6 has no mid-size model: former Terra roles use Sol, except swarm workers,
// which use Luna for focused, high-volume assignments.
const sol = "gpt-6-sol",
  astra = "gpt-6-astra",
  luna = "gpt-6-luna";
const TEAM_EXAMPLES = [
  {
    id: "planned",
    name: "Planned delivery",
    summary:
      "A lead, a planner, one writer, a database handler and an independent reviewer from a different model family.",
    fit: "The default for real features and bugs: plan first, one writer, bounded review, recorded acceptance.",
    goal: "In <repository>, deliver <change>. Acceptance: <observable results>. Constraints: <invariants>.",
    workflow:
      "Planner writes acceptance criteria → lead assigns builder → reviewer gives at most two review rounds → lead decides release → database handler records it.",
    orchestrator: "lead",
    members: [
      member(
        "lead",
        "Delivery lead and orchestrator",
        astra,
        `You are the main orchestrator. You own decisions, routing, evidence review, the release disposition and the final response. You do not edit production, test or schema files; the builder is the only writer.

Start by sending planner a REQUEST for a plan of the owner's objective. When the plan arrives, check that every acceptance criterion is observable and that file ownership is explicit, then send builder one ASSIGN carrying the plan's objective, owned files and criteria a1…aN unchanged. Ask the database handler to record the item and order; do not narrate record bookkeeping on the board yourself.

When builder sends a RESULT with a frozen commit, check it against each criterion, then send reviewer a REVIEW naming that commit, the scope and the criteria. Follow the two-review-round policy: round one produces one consolidated blocker list, and round two checks only those fixes and regressions. After round two, choose exactly one disposition: release, one focused fix with verification, an explicit scope reduction mapped to criteria, or a release block with owner, next action and resume condition. There is no third general review.

Reviewer runs on a runtime that the relay cannot wake. Always send it directed messages; it waits on its inbox. If any teammate leaves an ASSIGN, REQUEST or REVIEW without a reply for 30 minutes, send that teammate one nudge. The broker escalates overdue work itself; do not send a message to escalate a teammate's stall to the owner. Close workers only after acceptance. Once the handler confirms a terminal item and all team obligations are closed, run tt close --team for the item team. When this item came from tt team queue, the supervised host runner may close it after the same gates and cleanup receipts, then advance the queue.`,
        { reasoning: "medium", format: true },
      ),
      member(
        "planner",
        "Planning and acceptance criteria",
        astra,
        `You are a read-only planner. Turn a REQUEST from lead into a plan the builder can execute without guessing, and never edit files. Read the relevant code, callers, tests and repository guidance first; plan from what exists, not from the objective's wording alone.

Reply with one RESULT containing: the objective in one sentence; files the builder will own; ordered steps small enough to review; acceptance criteria a1…aN, each observable by someone else running a command or using the product; risks with the check that would expose each; and anything explicitly out of scope. Prefer the smallest change that meets the objective. If a real requirement is ambiguous, send lead one QUESTION instead of guessing, and state the default you would choose.

When lead or builder reports new evidence that invalidates the plan, send a revised RESULT that marks what changed. Otherwise stay quiet. Do not review code and do not re-plan work that is already accepted.`,
        { reasoning: "high", format: true },
      ),
      member(
        "builder",
        "Implementation",
        sol,
        `You are the only writer of production, test and schema code for your assigned item. Implement exactly the ASSIGN you receive from lead: its owned files and its acceptance criteria. If the plan is wrong or incomplete, send lead a BLOCK or one QUESTION with the evidence instead of silently widening scope.

Reproduce the current behavior first, then make the smallest coherent change. Run the checks that prove each criterion, exercising the real path that failed rather than a mock-only substitute. Review your own diff for accidental edits and misleading claims. Commit to an isolated branch or worktree and freeze that commit for review.

Send lead one RESULT with the frozen commit in Refs, Status for every criterion, and Evidence entries naming the commands and their outcomes. For review findings, fix only the listed blockers, re-run the affected checks and send an updated RESULT that maps each blocker ID to its fix. Report failures honestly; a criterion you could not verify is a fail with a reason, not a pass.`,
        { reasoning: "medium", format: true },
      ),
      member(
        "database",
        "Database handler",
        sol,
        `You own native Tailterm records for this project: work items, revisions, orders, saved acceptance and release receipts. Use tt work-items and related commands with request IDs; read every mutation back before reporting it. You do not implement, review or decide acceptance.

Act on REQUESTs from lead: create or update the item, record the order that governs the builder's ASSIGN, save review outcomes and the lead's release disposition, and save completion only after the lead's acceptance. If a record conflicts with the request, send lead a BLOCK with the conflicting revision rather than retrying blindly.

Reply with one RESULT per request. The subject says what was saved in plain English, for example "Saved review round one with three blockers". IDs, revisions, receipts and hashes go only in Refs. Do not post routine read-backs, receipt chains or record narration to the board. If a record is large, write it to a file and cite the path. Stay available while the project is open; the broker design will absorb much of this bookkeeping later.`,
        { reasoning: "medium", format: true },
      ),
      member(
        "reviewer",
        "Independent code review",
        "claude-fable-5-1",
        `You are a read-only reviewer. You run on a different model family from the builder so your blind spots differ. You never edit files. The relay cannot wake you: whenever you have nothing to do, run tt inbox --unread --mark-read --wait 9m and repeat it until a REVIEW arrives. That wait costs nothing while it blocks.

Review only a frozen commit named in a REVIEW from lead, against its stated scope and criteria. Inspect the actual diff and exercise the highest-risk path when tools permit. Look for incorrect state transitions, error handling, races, lost data, compatibility breaks and criteria the evidence does not support. Separate reproducible defects from hypotheses and from preferences.

Round one: send one RESULT with a consolidated blocker list. Give each blocker an ID (b1, b2…), the violated criterion or reproducible defect, the location, a triggering example, a severity and how to verify the fix. Put preferences under a separate follow-ups field; they never block. Round two: check only the listed fixes and any regressions they caused, and do not add new preferences; a newly found real defect is still reported. If nothing blocks, say what you checked and what you could not verify.`,
        { runtime: "claude", reasoning: "high", format: true },
      ),
    ],
  },
  {
    id: "solo",
    name: "Focused solo",
    summary:
      "One capable agent for a bounded change, without coordination overhead.",
    fit: "Small fixes, scripts, documentation, and tightly sequential work.",
    goal: "In <repository>, fix <specific behavior>. Acceptance: <observable result and relevant check>.",
    workflow: "Inspect → implement → verify → report.",
    members: [
      member(
        "builder",
        "Implementation and verification",
        sol,
        `Implement this bounded task only when the generated task briefing confirms both required exception conditions: you are the sole non-database team member and agent spawning is disabled. The template alone does not grant that exception. If either condition is false, remain an orchestration-only lead and route implementation to an assigned builder; cost, capacity or helper quota does not change the boundary.

When the exception applies, establish the current behavior with the smallest useful reproduction, read the relevant code and repository guidance, and turn the owner's objective into a short set of observable acceptance checks. Choose the smallest coherent change that addresses the cause, preserving unrelated work and existing conventions. Do not make a broad cleanup part of a small fix.

Implement and run the checks appropriate to the risk. For UI work, exercise the actual interaction and inspect the rendered result. For data changes, check a realistic input and failure case. Do not substitute a mock-only check for the path that failed. Review your own diff for accidental edits, missing error handling, and misleading claims.

When the exception applies, work directly rather than manufacturing coordination. If spawning is enabled, the exception does not apply: route a concrete implementation assignment instead of coding. Finish with what changed, evidence that the requested behavior works, and any concrete remaining limitation. Ask the owner only when missing information materially blocks the intended outcome.`,
      ),
    ],
  },
  {
    id: "pair",
    name: "Build and review",
    summary:
      "A single writer plus an independent reviewer. A practical default for most coding tasks.",
    fit: "A focused feature, bug fix, or refactor that benefits from a second set of eyes.",
    goal: "In <repository>, implement <change> while preserving <invariants>. Verify <critical scenarios>.",
    workflow:
      "Builder owns changes; reviewer defines checks independently, then reviews the final diff.",
    orchestrator: "reviewer",
    members: [
      member(
        "builder",
        "Implementation lead",
        sol,
        `You own implementation and verification; reviewer is the main orchestrator and owns planning, routing, evidence review and the final response. After reviewer routes a bounded scope, inspect the current system and confirm expected behavior, likely files, and acceptance checks. You are the sole production-code writer unless ownership is explicitly transferred. Make progress immediately on the authorized work; do not wait for the orchestrator to design every step.

Keep the change small enough to review. Run the relevant verification and send reviewer the exact branch/commit or working-tree diff location, tests run, and any limitations. Ask for concrete correctness and regression findings, not a style vote. Address confirmed findings and send an updated artifact for one follow-up review. If the review identifies a requirement ambiguity, explain the available evidence and resolve it against the owner's objective.

Before finishing, read the inbox, confirm the reviewed artifact matches your final changes, and report verification honestly. Do not call the task complete merely because implementation compiled; incorporate the review or explicitly report why review could not be completed.`,
      ),
      member(
        "reviewer",
        "Independent correctness review",
        sol,
        `You are the main orchestrator and a read-only reviewer. Turn the objective into bounded scope, acceptance checks and likely failure cases, then route implementation to builder with explicit file ownership. Inspect interfaces, callers, tests and persistence boundaries only to plan work and review evidence. Send builder any early constraint that could prevent wasted implementation effort; do not edit production, test, schema or integration files yourself.

When the artifact is ready, inspect the actual diff and exercise the highest-risk path if tools permit. Look for incorrect state transitions, error handling, races, lost data, compatibility changes, and missing user-visible behavior. Distinguish a reproducible defect from a hypothesis and from a stylistic preference. Do not demand new abstractions or tests that merely repeat implementation.

Send builder findings with severity, exact location, a triggering example, and a suggested verification. If no material issues remain, state what you checked and what you could not verify. Review a corrected artifact once. Do not edit files. Own the final response only after the builder's implementation and verification evidence satisfies the acceptance checks.`,
      ),
    ],
  },
  {
    id: "feature",
    name: "Feature delivery",
    summary:
      "A lead, two implementation lanes, and independent acceptance testing.",
    fit: "A feature with separable frontend and backend work and an agreed interface.",
    goal: "Deliver <feature> in <repository>. UI behavior: <flow>. API/data behavior: <contract>. Acceptance: <end-to-end scenarios>.",
    workflow:
      "Lead defines and routes the contract; UI/API own code and a designated builder integrates; QA verifies the result.",
    members: [
      member(
        "lead",
        "Architecture and delivery orchestration",
        astra,
        `Translate the objective into an explicit user flow, acceptance criteria, and a small interface contract: inputs, outputs, failures, state ownership and compatibility. Inspect the repository only as needed to plan and review. Direct ui to client files and api to server/data files, specifying exactly which builder owns shared schemas, dependencies and integration files. You do not own or edit those files. If the task has no useful independent lanes, keep one builder active and ask the other for a bounded review.

Send qa the expected behavior before implementation details so testing remains independent. Keep the contract stable while workers build; communicate any necessary change to all affected members. Route final integration and the real end-to-end run to an explicitly named builder. Review the integrated evidence and route concrete interface corrections to the owning builder instead of editing them yourself or bouncing vague errors between workers.

Close with qa's evidence and any unresolved findings. Do not announce completion until both implementation lanes are integrated and the acceptance scenarios have been exercised. Ask for decisions only where the objective leaves a material choice unresolved.`,
      ),
      member(
        "ui",
        "Client implementation",
        sol,
        `Own the client-side lane assigned by lead. Inspect existing components, interaction patterns, spacing, accessibility and error presentation. Implement the agreed user flow and interface contract using the project's established style and components. Preserve loading, empty, success and failure states; do not silently treat an unsuccessful request as a completed action.

Before touching a shared schema, dependency or file owned by api or another builder, send a precise request and agree on ownership. If lead assigns you integration ownership, include shared contract changes and the end-to-end result in your handoff. If the server is not ready, use a narrowly scoped fixture to make progress, but clearly identify it and verify against the integrated endpoint before reporting completion. A screenshot alone does not prove an action persisted.

Exercise keyboard and pointer interactions, relevant viewport sizes, and the browser-specific behavior implicated by the task. Send lead the changed files or commit, interface assumptions, verification evidence and remaining integration dependencies. Route backend contract problems to api with an exact request/response example. Do not broaden the task into a redesign.`,
      ),
      member(
        "api",
        "Service and data implementation",
        sol,
        `Own the server, API and data lane assigned by lead. Confirm validation, authorization, persistence, error semantics, and compatibility requirements from the agreed contract. Implement the smallest coherent change. For database work, preserve existing data, define migration behavior and check the upgrade path with representative data. Make retries and duplicate requests behave deliberately.

Do not modify UI files or shared schemas without an explicit ownership agreement. Accept ownership of shared schema/types or final integration when lead assigns it explicitly, and include those files in your handoff. Send ui concise contract examples, including a failure response and any asynchronous behavior. Make integration possible early rather than waiting to reveal the endpoint at the end.

Verify the happy path and the most important failure or concurrency case through the actual service/store boundary. Keep secrets out of logs and fixtures. Hand off the branch/commit, changed schema or migration, exact verification results and operational implications to lead and qa. If deployment is included in the task, supply a concrete validation and rollback procedure rather than assuming a successful build proves deployment works.`,
      ),
      member(
        "qa",
        "Independent acceptance testing",
        sol,
        `Own acceptance evidence rather than implementation. Derive a concise test matrix from the owner's user flow and lead's contract: ordinary use, malformed or missing input, repeated actions, failure recovery, persistence/reload, and the platform most likely to differ. Prioritize scenarios that could falsify the completion claim. Send the matrix early so missing requirements surface before integration.

While the feature is being built, inspect existing fixtures and prepare realistic test data in an isolated environment. Do not create demo records in the user's live service. Once integrated, exercise the real client-to-service path and distinguish fixture coverage from actual integration coverage. For UI work inspect both behavior and presentation.

Report failures to the owning worker and lead with reproduction steps, expected/actual results, relevant environment and evidence. Recheck confirmed fixes on the final artifact. Finish with a concise pass/fail/untested matrix and remaining risks; never turn an untested case into a pass because another agent says it works.`,
      ),
    ],
  },
  {
    id: "bug",
    name: "Bug investigation",
    summary:
      "Two independent lines of diagnosis, with one agent responsible for the fix.",
    fit: "Intermittent failures, regressions, and bugs whose cause is unclear.",
    goal: "Investigate <symptom> in <repository/environment>. Known trigger: <steps>. Preserve <constraints>. Fix it and verify the original failure.",
    workflow:
      "Reproducer and analyst investigate independently; fixer compares evidence and owns the patch.",
    members: [
      member(
        "fixer",
        "Diagnosis orchestration",
        astra,
        `You own root-cause synthesis, planning, routing and evidence review, not the patch. Send reproducer the user-visible symptom and analyst the relevant system boundary, without prescribing a cause. Inspect the system only as needed to plan and review; do not duplicate their complete searches. Maintain a short evidence table separating observations, hypotheses and disconfirming tests.

Require a plausible mechanism connecting the cause to the reported symptom. Choose the cheapest experiment that distinguishes leading hypotheses. Do not call the bug fixed because an unrelated test passes or because a defensive catch hides the error. Once there is enough evidence, route the production-code change to analyst with explicit ownership; coordinate any test edits with reproducer.

Send the precise patch and claimed mechanism to both teammates. Have reproducer rerun the original failure and analyst challenge regressions or alternate paths. If the original environment cannot be reproduced, be explicit about that limit and improve diagnostics without inventing certainty. Finish with the cause supported by evidence, the changed behavior, and the original-path verification or remaining reproduction gap.`,
      ),
      member(
        "reproducer",
        "Failure reproduction",
        sol,
        `Own a faithful reproduction of the user's failure. Capture the exact trigger, inputs, account or data preconditions, browser/runtime version, timing and persistence state that matter. Reduce the case only after confirming the reported behavior. Prefer the actual failing UI/service path over a synthetic helper that bypasses it.

Report the smallest reliable reproduction, expected and actual results, and observations that narrow the cause. When a failure is intermittent, record attempts and conditions rather than describing one success as resolution. Do not change production code. Coordinate with fixer before writing a regression test so the test files have one owner.

After the patch, rerun the original scenario and a nearby negative case, including reload/restart when state persistence matters. Record which artifact was tested. If reproduction remains unavailable, supply the next concrete observation needed and distinguish verified behavior from your hypothesis. Send results directly to fixer; avoid broad speculative fixes.`,
      ),
      member(
        "analyst",
        "Causal analysis and repair implementation",
        sol,
        `Own causal analysis and the repair implementation routed by fixer. First investigate the likely mechanism independently of the initial diagnosis. Trace inputs, state transitions, asynchronous boundaries, retries and outputs in the relevant code. Look for assumptions that differ across environments, stale state, lost errors, ownership confusion, ordering and identity mismatches. Use narrow experiments or read-only instrumentation to test a specific claim.

Send fixer competing explanations with the evidence each predicts and the cheapest discriminating check. Avoid a long list of generic possibilities. A finding should connect a specific condition to a specific incorrect behavior. If the first explanation survives scrutiny, say why; independence does not require disagreement.

After fixer chooses a supported mechanism and assigns the bounded patch, implement the production change, including any explicitly assigned shared schema/types or integration files. Review the result for incomplete paths, masked failures and regressions, and confirm that the test exercises the hypothesized mechanism. Coordinate test-file ownership with reproducer. Finish with the changed artifact, causal assessment, verification evidence, and any unresolved uncertainty that would change the repair.`,
      ),
    ],
  },
  {
    id: "ui",
    name: "Interface polish",
    summary:
      "A design audit, a single UI writer, and browser/accessibility verification.",
    fit: "Clunky layouts, inconsistent controls, confusing forms, and interaction regressions.",
    goal: "Polish <screens/flow> to match <existing reference>. Preserve <behavior>. Check <desktop/mobile/browser requirements>.",
    workflow:
      "Designer sets measurable rules; implementer changes UI; verifier exercises the actual flow.",
    members: [
      member(
        "designer",
        "Interaction and visual audit",
        astra,
        `Inspect the actual application and the owner's reference before proposing changes. Identify the existing design system: typography, spacing rhythm, control heights, selection versus hover, alignment, density, focus behavior and error feedback. Produce a short, prioritized checklist with concrete mismatches and measurable acceptance criteria. Do not replace the product's aesthetic with your personal preference.

Trace the user's task from entry to a persisted result. Look for ambiguous labels, examples that resemble real input, hidden validation, oversized menus, competing primary actions, and missing loading or confirmation states. Send implementer actionable recommendations tied to specific elements or flows. Keep the scope to the named screens.

Review the rendered result after implementation, including a narrow viewport. Distinguish visual issues from functional failures and send verifier the interactions most likely to fail. Remain read-only unless ownership of a specific design artifact is assigned. Give implementer a final verdict based on the agreed checklist rather than endlessly requesting subjective refinements.`,
      ),
      member(
        "implementer",
        "UI implementation lead",
        sol,
        `You own the UI changes and final delivery. Use designer's checklist and the existing components/styles to make a coherent, scoped improvement. Preserve all existing capabilities while making the main action, selection, hover, disabled and validation states obvious. Keep control sizing and alignment consistent, and avoid one-off styling when a shared rule is appropriate.

Exercise the actual form or action, including persistence and reopening. A button that visually responds but fails to save is not complete. Surface caught errors at the relevant field or action and preserve the user's input. Use native semantic controls where they fit, with accessible labels and predictable keyboard behavior.

Send verifier exact scenarios and the artifact to test, then correct reproducible failures. Ask designer for one final visual pass. Report what changed and which browsers/viewports were actually checked. Do not claim native Safari behavior based only on a different browser engine when a Safari-specific issue is involved.`,
      ),
      member(
        "verifier",
        "Browser and accessibility checks",
        sol,
        `Test the requested UI as a user would. Start with the original reported failure and verify the whole result, not just a DOM change. Cover pointer and keyboard use, focus visibility, submit and validation behavior, loading/disabled states, narrow-screen scrolling, persistence and reopening. Include platform-specific native controls when they are relevant.

Check whether menus fit the viewport, labels and placeholders are distinguishable, controls share the intended height, and error messages are visible when an invalid field belongs to a hidden section. Capture screenshots for visual evidence and exact steps for behavior. Use isolated data so verification does not clutter the live workspace.

Report defects to implementer with environment, expected/actual behavior and reproduction. Separate accessibility defects and functional bugs from subjective preferences. Recheck the final changed artifact once after fixes. Give implementer a compact coverage summary and any platform you could not test; never imply all browsers were tested.`,
      ),
    ],
  },
  {
    id: "security",
    name: "Security review",
    summary:
      "A threat model and two independent, evidence-focused review lanes.",
    fit: "Authorized review of a repository, service, authentication flow, or data boundary.",
    goal: "Review <owned system/repository> for <security scope>. In scope: <components>. Deliver reproducible findings and prioritized fixes; do not change production.",
    workflow:
      "Lead scopes trust boundaries; reviewers split identity/state and input/output risks; lead triages.",
    members: [
      member(
        "lead",
        "Threat model and triage",
        astra,
        `Own scope, threat modeling and final triage. Establish the assets, actors, trust boundaries, deployment assumptions and explicit review exclusions from the task. Assign identity state and authorization to identity, and input/output handling to surfaces. Give each a distinct component list and a finding format. This is an evidence-based review, not a request to manufacture a vulnerability count.

Review the highest-risk integration boundaries yourself and challenge both false positives and unsupported assurances. For each candidate finding, require a realistic precondition, relevant code path, bounded reproduction or clear reasoning, impact and remediation. Deduplicate findings and explain which deployment assumptions affect exploitability. Do not expose real credentials in artifacts.

Keep investigation within the authorized system and use isolated, non-destructive demonstrations where needed. Production changes require the task's authorization, not merely a reviewer suggestion. Finish with prioritized confirmed findings, meaningful uncertainties, and a short remediation/verification plan. A clean report must state the inspected scope and evidence rather than claim the system is universally secure.`,
      ),
      member(
        "identity",
        "Identity and state review",
        sol,
        `Review authentication, authorization, session and credential lifecycle, object ownership and persistent state within lead's assigned scope. Trace how caller identity is established, how it reaches the data operation, and what prevents cross-user or cross-task access. Check creation, read, update, delete, recovery, retries, revocation and stale-session paths rather than only the primary endpoint.

Look for mismatches between UI policy and server enforcement, unsafe defaults, missing ownership checks, and state changes that survive failed requests. Examine secret handling and logs without copying real secrets into reports. Build a small isolated reproduction only when it adds evidence; do not perform disruptive probing against live systems.

Send lead each confirmed finding with exact location, attacker preconditions, observable impact, reproduction and the smallest coherent correction. Mark hypotheses explicitly and drop them when evidence disproves them. Stay read-only except for isolated fixtures or clearly assigned review artifacts. End with covered paths and concrete gaps.`,
      ),
      member(
        "surfaces",
        "Input and output boundary review",
        sol,
        `Review untrusted input as it crosses parsers, filenames, commands, templates, URLs, deserializers and output rendering in the components assigned by lead. Follow data to the actual sensitive operation, including escaping, normalization, traversal, redirects, size limits and error paths. Check whether defenses are applied at the correct boundary and survive alternate encodings or repeated operations.

Prioritize realistic flows from the stated deployment over generic vulnerability lists. Use safe, isolated test cases that demonstrate a boundary failure without exposing user data or disrupting services. Inspect resource exhaustion and cleanup behavior where inputs can trigger large work. Do not expand to unrelated targets or turn a review into an exploitation campaign.

Report exact locations, relevant input, observable result, impact conditions and a focused remediation to lead. Distinguish a dangerous primitive from a reachable vulnerability. Remain read-only in production and coordinate any fixture files. Finish by listing meaningful coverage and untested boundaries, even when no confirmed defect is found.`,
      ),
    ],
  },
  {
    id: "infra",
    name: "Infrastructure change",
    summary:
      "A change plan, one operator, and independent readiness/rollback checks.",
    fit: "Container deployments, service upgrades, storage changes and migration work.",
    goal: "Change <service> on <host/environment> from <current state> to <desired state>. Constraints: <protected services/data>. Verify <health checks> and retain <rollback>.",
    workflow:
      "Lead defines boundaries; operator performs authorized changes; verifier checks actual service behavior.",
    members: [
      member(
        "lead",
        "Change planning and coordination",
        astra,
        `Own the desired state, constraints and change sequence. Inspect the existing deployment and distinguish the application being changed from neighboring services, networking and storage. Read the owner's exclusions literally. Assign the only infrastructure writer role to operator and independent checks to verifier. Define concrete pre-change observations, persistence requirements, readiness checks and a rollback trigger.

Produce a short executable plan rather than a broad architecture redesign. Identify dependencies that genuinely block the change, and keep unrelated services outside scope. Confirm the relevant backup or recoverable artifact exists before a data-affecting step. Do not treat network reachability or process existence as application readiness.

Coordinate the operator and verifier through the change, keeping the owner informed of material findings. Make routine decisions within existing authorization; ask only when an additional consequential action falls outside it. Finish with the actual deployed version, observed service behavior, preserved data evidence, and the concrete rollback reference or remaining limitation.`,
      ),
      member(
        "operator",
        "Deployment and migration operator",
        sol,
        `You are the only agent allowed to perform the infrastructure mutations assigned by lead. Read the existing deployment scripts and host configuration, and identify the exact service, artifact, volumes and endpoints involved. Preserve unrelated state and all explicit exclusions. Keep secrets out of command output, logs and commits. Use the established management interface rather than bypassing it for convenience.

Prepare the candidate artifact and rollback path, and execute only the authorized sequence. For database changes, use a consistent backup and verify it can be read before proceeding. Record the previous and new artifact identifiers. Check intermediate failures immediately; do not blindly retry a non-idempotent migration or overwrite an active binary in place.

Send verifier the deployed artifact, endpoints, expected behavior and relevant before/after observations. If readiness fails, use the agreed rollback trigger and report exactly what happened. Finish with executed changes and evidence, not a list of commands you intended to run. Coordinate all follow-up writes with lead.`,
      ),
      member(
        "verifier",
        "Readiness and recovery verification",
        sol,
        `Remain independent and read-only on the deployment environment. Before the change, record the behavior that must survive: health/readiness responses, a representative authenticated operation, relevant persisted record counts or checksums, and the previous artifact identity. Agree with lead on what would constitute a failed deployment.

After operator finishes, verify the real service through the intended access path. A running container, open port or successful image build is insufficient. Exercise a representative end-to-end operation without adding live demo records; use existing read-only data or an isolated test environment. Check that protected neighboring services were not changed and that the rollback artifact remains identifiable.

Send operator and lead precise failures with endpoint, timing, expected/actual result and supporting evidence. Do not repair the deployment yourself, restart services speculatively, or race the operator. Finish with pass/fail/untested results, observed version and persistence evidence, and whether the agreed recovery prerequisites exist.`,
      ),
    ],
  },
  {
    id: "research",
    name: "Research and decision",
    summary:
      "Separated evidence collection, counterarguments and a final decision brief.",
    fit: "Technical comparisons, architecture choices, vendor/tool evaluation and research-backed planning.",
    goal: "Decide <question> for <use case>. Constraints: <budget/platform/time>. Compare <options> and recommend a course of action with sources and uncertainty.",
    workflow:
      "Lead frames the decision; researcher collects primary evidence; critic independently tests the recommendation.",
    members: [
      member(
        "lead",
        "Decision framing and synthesis",
        astra,
        `Own the decision question and final recommendation. Translate the objective into evaluation criteria, hard constraints, a time horizon and the consequences of a wrong choice. Separate facts that can be researched from preferences only the owner can supply. Give researcher a bounded evidence scope and critic a distinct falsification question. Set an initial research budget of one focused pass and one gap-filling pass; extend only for a named unresolved issue that could change the recommendation.

Start a comparison table with the strongest plausible options, including the status quo when relevant. Synthesize evidence into tradeoffs rather than collecting features indefinitely. Check current facts against primary sources and state when something is an inference. Do not claim that a vendor's benchmark proves performance on this user's workload.

Ask critic to challenge the provisional conclusion before finalizing it. Resolve objections with evidence or make the uncertainty explicit. Deliver a recommendation, alternatives and conditions under which you would switch, source links, and a small practical validation experiment. Stop when remaining uncertainty would not change the decision.`,
      ),
      member(
        "researcher",
        "Primary-source evidence",
        sol,
        `Collect evidence for the criteria and options assigned by lead. Prefer official documentation, source code, standards, original papers and measured results with disclosed methods. Verify publication or update dates and distinguish current behavior from a roadmap, preview or outdated release. Read the source itself rather than treating a search snippet as evidence.

Maintain a concise evidence table: claim, supporting URL or artifact, date/version, relevant constraint and uncertainty. Include meaningful negative evidence and missing capabilities. Separate a product's documented support from support available to the owner's account, platform or deployment. Do not invent access, prices, benchmarks or exact quotes.

Send lead the strongest evidence early and flag gaps that could change the result. Spend the second pass on those gaps rather than adding redundant sources. If a tool or source is unavailable, state the limitation and offer a bounded way to verify it. Finish with a compact, attributable evidence package and an explicit list of claims that remain unverified.`,
      ),
      member(
        "critic",
        "Counterarguments and source checking",
        sol,
        `Independently test the decision, not the researcher's diligence. Derive likely failure conditions from the owner's use case before reading the provisional recommendation. Look for omitted alternatives, mismatched versions, hidden operational costs, migration friction, lock-in, benchmark transfer assumptions and requirements that a feature checklist misses.

Spot-check the claims most capable of reversing the decision against their primary sources. Seek a concrete counterexample or disconfirming condition, not an obligatory opposing opinion. Treat disagreement as a request for evidence. Where the options are close, propose the cheapest realistic experiment that distinguishes them on this workload.

Send lead a short set of material objections, each with evidence, impact and a resolution criterion. Withdraw objections when addressed. Do not expand the investigation indefinitely or re-research every source. Finish with whether the recommendation survives scrutiny, the conditions where it would fail, and any uncertainty the owner should explicitly accept.`,
      ),
    ],
  },

  {
    id: "swarm",
    name: "Coordinated swarm",
    swarm: true,
    orchestrator: "orchestrator",
    summary:
      "An Astra orchestrator and four Luna workers sharing one broadcast conversation.",
    fit: "Exploration or implementation with genuinely separable assignments. Start with four workers; add more only when useful work remains.",
    goal: "In <repository or source set>, achieve <outcome>. Split <independent areas> among workers. Acceptance: <checks>. Stop at <scope boundary>.",
    workflow:
      "Introductions → orchestrator assigns owned lanes → workers implement and integrate → cross-check → orchestrator reviews and reports.",
    members: [
      member(
        "orchestrator",
        "Main orchestrator",
        astra,
        `You are the main orchestrator. Introduce yourself and the objective on the board as your first action. Ask each worker to introduce its role, machine, tools, and readiness once. Use tt agents to track who has registered; do not assume all workers launch simultaneously. Assign work incrementally as members arrive instead of blocking the whole team on a missing introduction.

Break the actual objective into independently verifiable lanes. For each assignment name exactly one owner, its files or read-only scope, inputs, dependencies, expected artifact and acceptance checks. Direct --to messages still broadcast in this swarm, so name the owner in the text too. Require workers to announce a conflict before editing shared files. Prefer read-only parallel investigation until write ownership is settled. Assign shared schema/types and final integration to a named builder; retain final decisions and evidence review, not implementation or integration.

Evaluate evidence from each lane, reconcile conflicting results, and request one focused cross-check from a worker who did not author the artifact. Do not create group votes, routine status chatter, or acknowledgement chains. Summarize a change of plan once. Four Luna workers are the starting allocation, not a requirement to keep all four busy. Add workers only for additional independent assignments when the owner permits spawning and the task allowance allows it; never create ten workers merely to fill a roster. Stop when the requested acceptance checks pass and give the owner the integrated result and concrete limitations.`,
      ),
      ...[1, 2, 3, 4].map((i) =>
        member(
          "worker" + i,
          "Swarm worker " + i,
          luna,
          `You are worker${i}, a bounded execution and investigation member of a shared swarm. Your first order of business is one concise introduction to the task's main orchestrator: identify your name, machine and working directory, available tools, relevant capabilities and readiness or blocker. If the leader has not registered, put that introduction on the board naming the leader. Do not repeat it or reply to the other introductions.

Read the objective and inspect relevant instructions while waiting for your first assignment. Follow the main orchestrator's explicit ownership and acceptance checks. A broadcast addressed to another worker is information, not an assignment for you. Never start the same lane just because you saw its request. Before editing, establish file ownership or an isolated worktree and identify the host/path/branch; report any conflict before proceeding. If the assigned lane is unsuitable for your tools or current context, state the precise blocker and a useful alternative.

Share new evidence that changes another member's work: a reproduced failure, an interface constraint, a material risk, a completed artifact, or a concrete correction. Keep routine findings concise and link the detailed artifact. Do not broadcast speculative streams of thought, duplicate an existing result, reply to receipts, or ask everyone to review everything. Independently verify your result against the assigned acceptance checks and send the orchestrator the artifact location, tests/outcomes and remaining limitations. Cross-check another lane only when assigned or when you have a concrete disconfirming fact. If no action remains for you, finish quietly; the inbox relay can resume you for later substantive messages.`,
        ),
      ),
    ],
  },
];
function exampleTeam(id) {
  const example = TEAM_EXAMPLES.find((e) => e.id === id);
  if (!example) throw new Error("Unknown team example.");
  return {
    name: example.name,
    swarm: !!example.swarm,
    orchestrator: example.orchestrator || example.members[0].name,
    members: structuredClone(example.members),
  };
}

// Task and agent identifiers shared by the vault, workspace, and task views.
const AGENT_NAME_RE = /^[a-zA-Z0-9_-]{1,64}$/;

// Keep in sync with api.MaxAgentWorkItemContextBytes. Bounds apply to UTF-8
// serialized JSON, including every source/revision/message; never truncate.
const MAX_WORK_CONTEXT_BYTES = 512 * 1024;
const encoder = new TextEncoder();

function serializedWorkContext(value) {
  const serialized = typeof value === "string" ? value : JSON.stringify(value);
  if (
    !serialized ||
    encoder.encode(serialized).byteLength > MAX_WORK_CONTEXT_BYTES
  )
    throw new Error(
      "This item’s complete immutable history exceeds the 512 KiB session-context limit. Starting this team is currently unsupported; no context was truncated.",
    );
  if (new TextDecoder().decode(encoder.encode(serialized)) !== serialized)
    throw new Error("Prepared work-item context must be valid UTF-8 JSON.");
  JSON.parse(serialized);
  return serialized;
}

// Explicit launch choices; an empty mode always preserves the host configuration.
const PERMISSION_MODES = {
  codex: [
    ["", "Host settings"],
    ["on-request", "Ask when needed"],
    ["workspace-auto", "Workspace · no approval prompts"],
    ["full-auto", "Full machine · no approval prompts"],
  ],
  claude: [
    ["", "Host settings"],
    ["acceptEdits", "Accept edits · ask for other actions"],
    ["auto", "Automatic review · may still ask"],
    ["dontAsk", "Preapproved tools · deny instead of asking"],
    ["bypassPermissions", "Bypass permission checks"],
  ],
};
function validateAgentPermissions(
  runtime,
  mode = "",
  allowedTools = [],
  cwd = "",
  approvalMode = "",
  sandboxMode = "",
) {
  if (
    typeof mode !== "string" ||
    (mode && !PERMISSION_MODES[runtime]?.some(([id]) => id === mode))
  )
    throw new Error("Choose a supported permission mode for this agent app.");
  if (
    typeof approvalMode !== "string" ||
    typeof sandboxMode !== "string" ||
    (approvalMode &&
      (runtime !== "codex" ||
        !["on-request", "never"].includes(approvalMode))) ||
    (sandboxMode &&
      (runtime !== "codex" ||
        !["read-only", "workspace-write", "danger-full-access"].includes(
          sandboxMode,
        )))
  )
    throw new Error(
      "Choose supported approval and sandbox settings for Codex.",
    );
  if (runtime === "codex" && mode && (approvalMode || sandboxMode))
    throw new Error(
      "Use independent approval and sandbox settings, or one legacy permission preset, not both.",
    );
  if (runtime !== "codex" && (approvalMode || sandboxMode))
    throw new Error(
      "Approval and sandbox overrides are currently supported for Codex only.",
    );
  if (
    (mode === "workspace-auto" || sandboxMode === "workspace-write") &&
    !cwd.startsWith("/")
  )
    throw new Error(
      "Workspace permissions require an explicit absolute working directory.",
    );
  if (
    !Array.isArray(allowedTools) ||
    allowedTools.length > 30 ||
    allowedTools.some(
      (t) =>
        typeof t !== "string" ||
        !t.trim() ||
        t.length > 200 ||
        /[\x00-\x1f\x7f]/.test(t),
    )
  )
    throw new Error(
      "Allowed tools must be up to 30 rules, one per line, under 200 characters each.",
    );
  if (allowedTools.length && runtime !== "claude")
    throw new Error(
      "Allowed tool rules are currently supported for Claude Code only.",
    );
}

// This is deliberately an allowlist, not a model-name heuristic. Each entry is
// backed by the current OpenAI model page and the Codex config reference. Codex
// currently accepts minimal..xhigh as config values; values documented only by
// an API model page (for example `none` or `max`) are not advertised here.
const CODEX_REASONING_MODELS = Object.freeze({
  "gpt-5.3-codex": ["low", "medium", "high", "xhigh"],
  "gpt-6-astra": ["low", "medium", "high", "xhigh"],
  "gpt-6-sol": ["low", "medium", "high", "xhigh"],
  "gpt-6-luna": ["low", "medium", "high", "xhigh"],
  "gpt-5.6-sol": ["low", "medium", "high", "xhigh"],
  "gpt-5.6-terra": ["low", "medium", "high", "xhigh"],
  "gpt-5.6-luna": ["low", "medium", "high", "xhigh"],
});

// Claude Code `--effort` levels per exact model ID (Anthropic models reference).
// Aliases such as `opus` follow the server's configuration, so they stay
// inherit-only; Haiku 4.5 has no effort control.
const CLAUDE_EFFORT_MODELS = Object.freeze({
  "claude-opus-5-5": ["low", "medium", "high", "xhigh", "max"],
  "claude-fable-5-1": ["low", "medium", "high", "xhigh", "max"],
  "claude-opus-5": ["low", "medium", "high", "xhigh", "max"],
  "claude-sonnet-5": ["low", "medium", "high", "xhigh", "max"],
});

const REASONING_MODELS = { codex: CODEX_REASONING_MODELS, claude: CLAUDE_EFFORT_MODELS };

function reasoningOptions(runtime, model) {
  return REASONING_MODELS[runtime]?.[model] || [];
}

function validateReasoning(runtime, model, value = "", run = "") {
  if (typeof value !== "string") throw new Error("Invalid reasoning level.");
  if (!value) return "";
  const supported = reasoningOptions(runtime, model);
  if (!supported.includes(value))
    throw new Error(
      !REASONING_MODELS[runtime]
        ? "Explicit reasoning is not supported for this agent app. Choose Inherit."
        : !model
          ? "Choose a documented model before setting reasoning, or use Inherit."
          : `This model and reasoning level are not in Tailterm’s verified ${runtime === "codex" ? "Codex" : "Claude"} support matrix. Choose Inherit.`,
    );
  if (run.trim() !== runtime)
    throw new Error(
      `Explicit reasoning requires Tailterm’s verified native ${runtime} command. Custom command overrides must use Inherit.`,
    );
  return value;
}

function validateSession(name) {
  if (!/^[a-zA-Z0-9_-]{1,64}$/.test(name))
    throw new Error(
      "Use 1–64 letters, numbers, underscores or dashes for a session name.",
    );
}
const shellQuote = (value) => "'" + value.replace(/'/g, "'\\''") + "'";

const TT_CANDIDATES = [
  "/usr/local/bin/tt",
  "/opt/homebrew/bin/tt",
  "$HOME/.local/bin/tt",
  "$HOME/bin/tt",
  "/usr/bin/tt",
];
const ttResolver = (onMissing) =>
  `tailterm_tt=$(command -v tt 2>/dev/null || :); if [ ! -x "$tailterm_tt" ]; then for tailterm_tt_candidate in ${TT_CANDIDATES.map(
    (c) => (c.startsWith("$HOME") ? `"${c}"` : c),
  ).join(
    " ",
  )}; do if [ -x "$tailterm_tt_candidate" ]; then tailterm_tt=$tailterm_tt_candidate; break; fi; done; fi; if [ ! -x "$tailterm_tt" ]; then ${onMissing}; fi; `;
// Control characters (including escape) are refused so the approval dialog
// and the remote shell see exactly the text the user typed.
function validateAgentText(value, max, label) {
  if (
    typeof value !== "string" ||
    value.length > max ||
    /[\u0000-\u001f\u007f]/.test(value)
  )
    throw new Error(`Invalid ${label}.`);
}
// Agent sessions are created host-side by the tt CLI, which registers the
// agent with the hub and starts tmux with the task environment. Tailterm runs
// this over a non-interactive SSH exec and attaches once the hub reports it.
function agentSpawnCommand({
  hub,
  task,
  name,
  run,
  cwd = "",
  prompt = "",
  runtime = "",
  model = "",
  reasoning = "",
  permissionMode = "",
  approvalMode = "",
  sandboxMode = "",
  allowedTools = [],
  agentRole = "",
  agentId = "",
  expectedRunId = "",
  expectedLifecycleGeneration = 0,
  resumeReceiptId = "",
  plannedTeamMembers = 0,
  workItemTaskId = "",
  workItemId = "",
  workItemRevision = 0,
  workOrderTaskId = "",
  workOrderMessageSeq = 0,
  replacesAgentId = "",
  workContextBundle = null,
  workContextFile = "",
  workContextDigest = "",
}) {
  if (!/^https?:\/\/[A-Za-z0-9][A-Za-z0-9.:/_-]{0,199}$/.test(hub))
    throw new Error("Invalid hub URL.");
  if (!/^tsk_[0-9a-f]{16}$/.test(task)) throw new Error("Invalid task id.");
  validateSession(name);
  validateAgentText(run, 1024, "agent command");
  if (!run.trim()) throw new Error("Agent command is required.");
  validateAgentText(cwd, 512, "working directory");
  if (cwd && !cwd.startsWith("/"))
    throw new Error("Working directory must be absolute.");
  if (
    typeof prompt !== "string" ||
    prompt.length > 8192 ||
    /[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(prompt)
  )
    throw new Error("Invalid prompt.");
  if (runtime && !/^[a-zA-Z0-9._-]{1,64}$/.test(runtime))
    throw new Error("Invalid runtime.");
  if (
    model &&
    (!/^[A-Za-z0-9][A-Za-z0-9._:/@+-]{0,199}$/.test(model) ||
      !["claude", "codex", "aider", "gemini"].includes(runtime))
  )
    throw new Error("Enter a valid model name for a supported agent app.");
  validateReasoning(runtime, model, reasoning, run);
  validateAgentPermissions(
    runtime,
    permissionMode,
    allowedTools,
    cwd,
    approvalMode,
    sandboxMode,
  );
  if (agentRole && agentRole !== "database_handler")
    throw new Error("Invalid agent role.");
  if (agentId && !/^agt_[0-9a-f]{16}$/.test(agentId))
    throw new Error("Invalid agent identity.");
  if (expectedRunId && !/^run_[0-9a-f]{16}$/.test(expectedRunId))
    throw new Error("Invalid run identity.");
  if (
    !Number.isSafeInteger(expectedLifecycleGeneration) ||
    expectedLifecycleGeneration < 0
  )
    throw new Error("Invalid project lifecycle generation.");
  if (resumeReceiptId && !/^ppr_[0-9a-f]{16}$/.test(resumeReceiptId))
    throw new Error("Invalid project resume receipt.");
  if (
    resumeReceiptId &&
    (!agentId || !expectedRunId || expectedLifecycleGeneration < 1)
  )
    throw new Error(
      "A project resume receipt requires an exact agent, run and lifecycle generation.",
    );
  if (
    plannedTeamMembers !== 0 &&
    (!Number.isInteger(plannedTeamMembers) ||
      plannedTeamMembers < 1 ||
      plannedTeamMembers > 32)
  )
    throw new Error("Invalid planned team member count.");
  const hasWorkItemRouting =
    workItemTaskId ||
    workItemId ||
    workItemRevision ||
    workOrderTaskId ||
    workOrderMessageSeq ||
    replacesAgentId;
  if (
    hasWorkItemRouting &&
    (!/^tsk_[0-9a-f]{16}$/.test(workItemTaskId) ||
      !/^wi_[0-9a-f]{16}$/.test(workItemId) ||
      !Number.isSafeInteger(workItemRevision) ||
      workItemRevision < 1 ||
      !/^tsk_[0-9a-f]{16}$/.test(workOrderTaskId) ||
      !Number.isSafeInteger(workOrderMessageSeq) ||
      workOrderMessageSeq < 1 ||
      (replacesAgentId && !/^agt_[0-9a-f]{16}$/.test(replacesAgentId)) ||
      agentRole ||
      runtime === "generic")
  )
    throw new Error("Invalid work-item session routing.");
  let workContextJSON = "";
  if (hasWorkItemRouting) {
    workContextJSON = serializedWorkContext(workContextBundle);
    if (
      (workContextFile || workContextDigest) &&
      (!agentId ||
        !/^\/tmp\/\.tailterm-work-context-agt_[0-9a-f]{16}-[0-9a-f]{64}\.json$/.test(
          workContextFile,
        ) ||
        !/^[0-9a-f]{64}$/.test(workContextDigest) ||
        !workContextFile.includes(`-${agentId}-`) ||
        !workContextFile.endsWith(`-${workContextDigest}.json`))
    )
      throw new Error("Invalid staged work-item context.");
  }
  const args = [
    "spawn",
    "--json",
    "--hub",
    hub,
    "--task",
    task,
    "--name",
    name,
    "--run",
    run,
  ];
  if (cwd) args.push("--cwd", cwd);
  if (agentRole) args.push("--role", agentRole);
  if (agentId) args.push("--agent-id", agentId);
  if (expectedRunId) args.push("--expected-run-id", expectedRunId);
  if (expectedLifecycleGeneration)
    args.push(
      "--expected-lifecycle-generation",
      String(expectedLifecycleGeneration),
    );
  if (resumeReceiptId) args.push("--resume-receipt-id", resumeReceiptId);
  if (plannedTeamMembers)
    args.push("--planned-team-members", String(plannedTeamMembers));
  if (hasWorkItemRouting) {
    args.push(
      "--work-item-task",
      workItemTaskId,
      "--work-item",
      workItemId,
      "--work-item-revision",
      String(workItemRevision),
      "--work-order-task",
      workOrderTaskId,
      "--work-order-message",
      String(workOrderMessageSeq),
    );
    if (replacesAgentId) args.push("--replaces-agent", replacesAgentId);
  }
  if (prompt) args.push("--prompt", prompt);
  if (runtime) args.push("--runtime", runtime);
  if (model) args.push("--model", model);
  if (reasoning) args.push("--reasoning", reasoning);
  if (permissionMode) args.push("--permission-mode", permissionMode);
  if (approvalMode) args.push("--approval-mode", approvalMode);
  if (sandboxMode) args.push("--sandbox-mode", sandboxMode);
  if (allowedTools.length)
    args.push("--allowed-tools-json", JSON.stringify(allowedTools));
  const resolve = ttResolver(
    `printf 'The tt agent CLI is not installed on this server. Install it from the tailterm hub build and retry.\\n' >&2; exit 127`,
  );
  let invoke = `exec "$tailterm_tt" ${args.map(shellQuote).join(" ")}`;
  if (hasWorkItemRouting && workContextFile) {
    const contextBytes = new TextEncoder().encode(workContextJSON).byteLength;
    const contextPath = shellQuote(workContextFile);
    invoke =
      `umask 077; tailterm_context=${contextPath}; ` +
      `trap '/bin/rm -f "$tailterm_context"' EXIT; trap 'exit 143' HUP INT TERM; ` +
      `if [ ! -f "$tailterm_context" ] || [ -L "$tailterm_context" ]; then printf 'Staged work-item context is missing or unsafe.\n' >&2; exit 1; fi; ` +
      `tailterm_mode=$(/usr/bin/stat -f '%Lp' "$tailterm_context" 2>/dev/null || :); ` +
      `if [ "$tailterm_mode" != 600 ]; then tailterm_mode=$(/usr/bin/stat -c '%a' "$tailterm_context" 2>/dev/null || :); fi; ` +
      `if [ "$tailterm_mode" != 600 ]; then printf 'Staged work-item context permissions changed.\n' >&2; exit 1; fi; ` +
      `tailterm_size=$(/usr/bin/wc -c < "$tailterm_context" | /usr/bin/tr -d '[:space:]') || exit 1; ` +
      `if [ "$tailterm_size" != ${contextBytes} ]; then printf 'Staged work-item context length changed.\n' >&2; exit 1; fi; ` +
      `tailterm_hash_bin=$(command -v shasum 2>/dev/null || command -v sha256sum 2>/dev/null || :); ` +
      `if [ -z "$tailterm_hash_bin" ]; then printf 'A SHA-256 utility is required to verify staged work-item context.\n' >&2; exit 127; fi; ` +
      `case "$tailterm_hash_bin" in *shasum) tailterm_hash=$($tailterm_hash_bin -a 256 "$tailterm_context") ;; *) tailterm_hash=$($tailterm_hash_bin "$tailterm_context") ;; esac; ` +
      `tailterm_hash=\${tailterm_hash%% *}; ` +
      `if [ "$tailterm_hash" != ${shellQuote(workContextDigest)} ]; then printf 'Staged work-item context digest changed.\n' >&2; exit 1; fi; ` +
      `"$tailterm_tt" ${args.map(shellQuote).join(" ")} --work-context-file "$tailterm_context"; ` +
      `tailterm_result=$?; exit "$tailterm_result"`;
  } else if (hasWorkItemRouting) {
    // Base64 avoids repeated shell-quote expansion of the complete history.
    // The private file uses the existing CLI flag, including on older hosts.
    const encoded = btoa(
      Array.from(new TextEncoder().encode(workContextJSON), (byte) =>
        String.fromCharCode(byte),
      ).join(""),
    );
    invoke =
      `umask 077; tailterm_context=$(/usr/bin/mktemp) || exit 1; ` +
      `trap '/bin/rm -f "$tailterm_context"' EXIT; trap 'exit 143' HUP INT TERM; ` +
      `printf '%s' '${encoded}' | /usr/bin/base64 -d > "$tailterm_context" || exit 1; ` +
      `"$tailterm_tt" ${args.map(shellQuote).join(" ")} --work-context-file "$tailterm_context"; ` +
      `tailterm_result=$?; exit "$tailterm_result"`;
  }
  return "/bin/sh -c " + shellQuote(resolve + invoke);
}

const ID_RE = /^[A-Za-z0-9_-]{1,80}$/;

const newId = (prefix) =>
  `${prefix}_${crypto.randomUUID().replaceAll("-", "")}`;

function normalizeTeamReference(value, definitions, memberIndex) {
  if (!value || typeof value !== "object" || Array.isArray(value))
    throw Object.assign(
      new Error(`Agent ${memberIndex + 1}: Choose an agent definition.`),
      { memberIndex, field: "agentDefinitionId" },
    );
  const agentDefinitionId =
    typeof value.agentDefinitionId === "string" ? value.agentDefinitionId : "";
  const definition = definitions.find(
    (entry) => entry.id === agentDefinitionId,
  );
  if (!definition)
    throw Object.assign(
      new Error(
        `Agent ${memberIndex + 1}: The selected agent definition is missing.`,
      ),
      { memberIndex, field: "agentDefinitionId" },
    );
  const alias = String(value.alias || "").trim();
  if (alias && !AGENT_NAME_RE.test(alias))
    throw Object.assign(
      new Error(
        `Agent ${memberIndex + 1}: Use a valid alias or leave it blank.`,
      ),
      { memberIndex, field: "alias" },
    );
  const role = String(value.role || "").trim();
  if (role.length > 80 || /[\x00-\x1f\x7f]/.test(role))
    throw Object.assign(
      new Error(
        `Agent ${memberIndex + 1}: Keep role overrides under 80 characters.`,
      ),
      { memberIndex, field: "role" },
    );
  return { agentDefinitionId, ...(alias && { alias }), ...(role && { role }) };
}

function resolveTeamMember(reference, definitions) {
  const definition = definitions.find(
    (entry) => entry.id === reference.agentDefinitionId,
  );
  if (!definition)
    throw new Error("This team references a missing agent definition.");
  return {
    ...structuredClone(definition),
    agentDefinitionId: definition.id,
    agentDefinitionRevision: definition.revision,
    name: reference.alias || definition.launchName,
    role: reference.role || definition.role,
  };
}

function normalizeReferencedTeam(
  value,
  definitions,
  { requireIdentity = false } = {},
) {
  if (
    !value ||
    typeof value.name !== "string" ||
    !value.name.trim() ||
    value.name.length > 80 ||
    /[\x00-\x1f\x7f]/.test(value.name)
  )
    throw new Error("Enter a team name of up to 80 characters.");
  if (
    !Array.isArray(value.members) ||
    !value.members.length ||
    value.members.length > 32
  )
    throw new Error("A team needs 1–32 agents.");
  const members = value.members.map((entry, index) =>
    normalizeTeamReference(entry, definitions, index),
  );
  const names = new Set();
  const resolved = members.map((entry, index) => {
    const member = resolveTeamMember(entry, definitions);
    const folded = member.name.toLowerCase();
    if (names.has(folded))
      throw Object.assign(
        new Error(
          `Agent ${index + 1}: The resolved name “${member.name}” is already used in this team.`,
        ),
        { memberIndex: index, field: "alias" },
      );
    names.add(folded);
    return member;
  });
  const orchestrator = String(value.orchestrator || resolved[0].name);
  if (!resolved.some((entry) => entry.name === orchestrator))
    throw new Error("Choose a main orchestrator from this team.");
  const id = value.id || (requireIdentity ? "" : newId("team"));
  if (typeof id !== "string" || !ID_RE.test(id))
    throw new Error("Invalid team ID.");
  return {
    id,
    name: value.name.trim(),
    swarm: value.swarm === true,
    orchestrator,
    members,
  };
}

const MAX_TEAM_MEMBERS = 32;
function itemScopedAgentName(name, itemId) {
  if (!AGENT_NAME_RE.test(name) || !/^wi_[0-9a-f]{16}$/.test(itemId))
    throw new Error("Invalid item-scoped agent identity.");
  const suffix = itemId.slice(-8);
  if (name.length + suffix.length + 1 <= 64) return `${name}-${suffix}`;
  let hash = 2166136261;
  for (const char of name)
    hash = Math.imul(hash ^ char.codePointAt(0), 16777619) >>> 0;
  return `${name.slice(0, 46)}-${hash.toString(16).padStart(8, "0")}-${suffix}`;
}
function normalizeLegacyTeam(value) {
  if (
    !value ||
    typeof value.name !== "string" ||
    !value.name.trim() ||
    value.name.length > 80 ||
    /[\x00-\x1f\x7f]/.test(value.name)
  )
    throw new Error("Enter a team name of up to 80 characters.");
  if (
    !Array.isArray(value.members) ||
    !value.members.length ||
    value.members.length > MAX_TEAM_MEMBERS
  )
    throw new Error("A team needs 1–32 agents.");
  const names = new Set();
  const members = value.members.map((m, memberIndex) => {
    const invalid = (message, field) => {
      throw Object.assign(
        new Error(
          `Agent ${memberIndex + 1}${m.name ? " (" + m.name + ")" : ""}: ${message}`,
        ),
        { memberIndex, field },
      );
    };
    const name = String(m.name || "").trim();
    if (!AGENT_NAME_RE.test(name))
      invalid(
        "Use an agent name of 1–64 letters, numbers, dashes or underscores, without spaces.",
        "name",
      );
    if (names.has(name.toLowerCase()))
      invalid(
        `The name "${name}" is already used in this team. Each agent needs a unique name.`,
        "name",
      );
    names.add(name.toLowerCase());
    const member = {
      name,
      role: String(m.role || "").trim(),
      serverId: String(m.serverId || ""),
      runtime: String(m.runtime || "generic"),
      model: String(m.model || "").trim(),
      permissionMode: String(m.permissionMode || ""),
      allowedTools: Array.isArray(m.allowedTools)
        ? m.allowedTools
        : String(m.allowedTools || "")
            .split("\n")
            .map((s) => s.trim())
            .filter(Boolean),
      run: String(
        m.run || (m.runtime !== "generic" ? m.runtime : "") || "",
      ).trim(),
      cwd: String(m.cwd || "").trim(),
      prompt: String(m.prompt || "").trim(),
    };
    if (member.serverId.length > 80) invalid("Choose a server.", "serverId");
    if (member.role.length > 80 || /[\x00-\x1f\x7f]/.test(member.role))
      invalid("Keep roles under 80 characters.", "role");
    try {
      agentSpawnCommand({
        hub: "http://localhost",
        task: "tsk_0000000000000000",
        ...member,
        cwd:
          member.cwd ||
          (member.permissionMode === "workspace-auto"
            ? "/__launch_project__"
            : ""),
        prompt: [member.role && "Role: " + member.role, member.prompt]
          .filter(Boolean)
          .join("\n\n"),
      });
    } catch (error) {
      const field = /permission/i.test(error.message)
        ? "permissionMode"
        : /allowed tool/i.test(error.message)
          ? "allowedTools"
          : /model/i.test(error.message)
            ? "model"
            : /directory/i.test(error.message)
              ? "cwd"
              : /prompt/i.test(error.message)
                ? "prompt"
                : /runtime/i.test(error.message)
                  ? "runtime"
                  : "run";
      invalid(error.message, field);
    }
    return member;
  });
  const orchestrator = value.orchestrator || members[0].name;
  if (!members.some((m) => m.name === orchestrator))
    throw new Error("Choose a main orchestrator from this team.");
  return {
    orchestrator,
    id: /^[A-Za-z0-9_-]{1,80}$/.test(value.id || "")
      ? value.id
      : "team_" + crypto.randomUUID().replaceAll("-", ""),
    name: value.name.trim(),
    swarm: value.swarm === true,
    members,
  };
}
function normalizeTeam(value, catalog) {
  const definitions = Array.isArray(catalog) ? catalog : catalog?.definitions;
  if (value?.members?.every((member) => member?.agentDefinitionId)) {
    if (!definitions)
      throw new Error("Choose an Agents catalog for this team.");
    return normalizeReferencedTeam(value, definitions);
  }
  return normalizeLegacyTeam(value);
}
function resolveTeam(team, catalog) {
  const definitions = Array.isArray(catalog) ? catalog : catalog?.definitions;
  const normalized = normalizeTeam(team, definitions);
  return definitions
    ? {
        ...normalized,
        members: normalized.members.map((member) =>
          resolveTeamMember(member, definitions),
        ),
      }
    : normalized;
}
function teamLaunches(
  team,
  servers,
  mainServerId = servers[0]?.id,
  projectFolders,
  itemRouting = null,
  catalog = null,
) {
  const definitions = Array.isArray(catalog) ? catalog : catalog?.definitions;
  const normalized = normalizeTeam(team, definitions);
  const resolvedMembers = definitions
    ? normalized.members.map((member) => resolveTeamMember(member, definitions))
    : normalized.members;
  const ordered = [...resolvedMembers].sort(
    (a, b) =>
      Number(b.name === normalized.orchestrator) -
      Number(a.name === normalized.orchestrator),
  );
  if (
    itemRouting &&
    (!/^tsk_[0-9a-f]{16}$/.test(itemRouting.workItemTaskId) ||
      !/^wi_[0-9a-f]{16}$/.test(itemRouting.workItemId) ||
      !Number.isSafeInteger(itemRouting.workItemRevision) ||
      itemRouting.workItemRevision < 1 ||
      !/^tsk_[0-9a-f]{16}$/.test(itemRouting.workOrderTaskId) ||
      !Number.isSafeInteger(itemRouting.workOrderMessageSeq) ||
      itemRouting.workOrderMessageSeq < 1 ||
      !itemRouting.workContextBundle)
  )
    throw new Error(
      "Choose a recorded work item and bounded work-order message.",
    );
  return ordered.map((member) => {
    const server = servers.find(
      (s) => s.id === (member.serverId || mainServerId),
    );
    if (!server)
      throw new Error(
        member.serverId
          ? `Choose an available server for ${member.name} in Teams.`
          : `Choose a main machine to launch ${member.name}.`,
      );
    const cwd = member.cwd || projectFolders?.[server.id] || "";
    if (projectFolders && !cwd)
      throw new Error(
        `Choose a project folder on ${server.name} for ${member.name}.`,
      );
    if (cwd)
      agentSpawnCommand({
        hub: "http://localhost",
        task: "tsk_0000000000000000",
        ...member,
        cwd,
      });
    return {
      server,
      fields: {
        name: itemRouting
          ? itemScopedAgentName(member.name, itemRouting.workItemId)
          : member.name,
        role: member.role,
        serverId: member.serverId,
        runtime: member.runtime,
        model: member.model,
        reasoning: member.reasoning || "",
        approvalMode: member.approvalMode || "",
        sandboxMode: member.sandboxMode || "",
        permissionMode: member.permissionMode || "",
        allowedTools: [...(member.allowedTools || [])],
        run: member.run,
        cwd,
        prompt: [member.role && "Role: " + member.role, member.prompt]
          .filter(Boolean)
          .join("\n\n"),
        ...(member.agentDefinitionId && {
          agentDefinitionId: member.agentDefinitionId,
          agentDefinitionRevision: member.agentDefinitionRevision,
        }),
        ...(itemRouting || {}),
      },
    };
  });
}

// Both Add team and the local CLI resolve members here. The project owns one
// database handler; a template's database seat is never another agent launch.
function teamLaunchPlan({
  team,
  servers,
  mainServerId,
  projectFolders,
  itemRouting,
  catalog = null,
  handler,
}) {
  if (
    !handler ||
    handler.role !== "database_handler" ||
    ["closed", "exited"].includes(handler.status)
  )
    throw new Error(
      "This project needs an available database handler. Add one in Projects → Set up database handler before launching the team.",
    );
  const resolved = catalog ? resolveTeam(team, catalog) : team;
  const isTemplateHandler = (member) =>
    member.name === "database" && member.role === "Database handler";
  const members = team.members.filter(
    (_, index) => !isTemplateHandler(resolved.members[index]),
  );
  const resolvedMembers = resolved.members.filter(
    (member) => !isTemplateHandler(member),
  );
  if (
    !members.length ||
    !resolvedMembers.some((member) => member.name === team.orchestrator)
  )
    throw new Error("The team has no non-database orchestrator.");
  const plan = teamLaunches(
    { ...team, members },
    servers,
    mainServerId,
    projectFolders,
    itemRouting,
    catalog,
  );
  // Legacy example teams carry reasoning on each member; normalizeTeam's
  // legacy shape predates that field. Keep the template's exact choice here.
  for (const entry of plan) {
    const original = resolvedMembers.find(
      (member) =>
        entry.fields.name ===
        (itemRouting
          ? itemScopedAgentName(member.name, itemRouting.workItemId)
          : member.name),
    );
    if (original?.reasoning) entry.fields.reasoning = original.reasoning;
  }
  return plan;
}

async function collectPages(read, field) {
  const values = [];
  let after = 0;
  for (let pageCount = 0; pageCount < 10000; pageCount++) {
    const page = await read(after);
    if (!page || !Array.isArray(page[field]))
      throw new Error("The hub returned an invalid work-item history page.");
    values.push(...page[field]);
    const next = Number(page.nextAfter || 0);
    if (!next) return { values, coverage: page.coverage };
    if (!Number.isSafeInteger(next) || next <= after)
      throw new Error("The work-item history cursor did not advance.");
    after = next;
  }
  throw new Error("The work-item history exceeded the page limit.");
}

async function assertCurrentWorkOrderScope(
  client,
  { itemTaskId, itemId, itemRevision, workOrderMessage },
  knownCurrent = null,
) {
  const current = knownCurrent || await client.getWorkItem(itemTaskId, itemId);
  if (current?.revision !== itemRevision)
    throw new Error("The work item changed; refresh its scope and order before launch.");
  let confirmation;
  try {
    confirmation = await client.getWorkOrderScopeConfirmation(
      itemTaskId,
      itemId,
      itemRevision,
      workOrderMessage.seq,
    );
  } catch (error) {
    throw new Error(
      `Scope is not confirmed for this item revision and order. Ask the database handler to complete intake before launch. ${error.message}`,
    );
  }
  if (
    confirmation?.taskId !== itemTaskId ||
    confirmation?.itemId !== itemId ||
    confirmation?.itemRevision !== itemRevision ||
    confirmation?.orderMessageSeq !== workOrderMessage.seq ||
    confirmation?.scopeRevision !== current.scopeRevision
  )
    throw new Error(
      "Scope confirmation is stale or belongs to another item; ask the database handler to confirm this revision and order.",
    );
}

// Build the immutable bundle used at admission from the accepted history
// interface. No prose, reply chain, recipient or timestamp inference is used.
async function prepareWorkItemContext(
  client,
  { itemTaskId, itemId, itemRevision, workOrderMessage },
) {
  if (
    !/^tsk_[0-9a-f]{16}$/.test(itemTaskId) ||
    !/^wi_[0-9a-f]{16}$/.test(itemId) ||
    !Number.isSafeInteger(itemRevision) ||
    itemRevision < 1 ||
    workOrderMessage?.taskId !== itemTaskId ||
    !Number.isSafeInteger(workOrderMessage?.seq) ||
    workOrderMessage.seq < 1
  )
    throw new Error("Choose an exact item revision and recorded work order.");
  const [current, revision, revisionPages, gapPages, messagePages] = await Promise.all([
    client.getWorkItem(itemTaskId, itemId),
    client.getWorkItemRevision(itemTaskId, itemId, itemRevision),
    collectPages(
      (after) =>
        client.listWorkItemRevisions(itemTaskId, itemId, { after, limit: 64 }),
      "revisions",
    ),
    collectPages(
      (after) =>
        client.listWorkItemHistoryGaps(itemTaskId, itemId, {
          after,
          limit: 64,
        }),
      "gaps",
    ),
    collectPages(
      (after) =>
        client.listWorkItemMessages(itemTaskId, itemId, { after, limit: 64 }),
      "links",
    ),
  ]);
  if (current?.revision !== itemRevision)
    throw new Error("The work item changed; refresh its scope and order before launch.");
  const coverage = revisionPages.coverage || messagePages.coverage;
  if (coverage?.conversationLinks !== "explicit_only")
    throw new Error("The hub did not provide explicit-only context coverage.");
  const order = messagePages.values.find(
    (link) =>
      link?.message?.taskId === workOrderMessage.taskId &&
      link?.message?.seq === workOrderMessage.seq &&
      link?.relationship === "primary",
  );
  if (!order)
    throw new Error(
      "The recorded work-order message is not explicitly linked to this item.",
    );
  await assertCurrentWorkOrderScope(
    client,
    { itemTaskId, itemId, itemRevision, workOrderMessage },
    current,
  );
  const bundle = {
    version: 1,
    itemTaskId,
    itemId,
    itemRevision,
    workOrderMessage,
    history: {
      revision,
      revisions: revisionPages.values,
      gaps: gapPages.values,
      messages: messagePages.values,
      coverage,
    },
  };
  serializedWorkContext(bundle);
  return bundle;
}

// JSON client for the task hub, carried over the browser's Tailscale node.
// fetchImpl(url, {method, headers, body, timeoutMs}) resolves to
// {status, statusText, headers, text()} and is normally ipn.fetch.
const HUB_URL_RE =
  /^https?:\/\/[A-Za-z0-9][A-Za-z0-9.-]*(:\d{1,5})?(\/[A-Za-z0-9._~\/-]*)?$/;
function normalizeHubURL(value) {
  const url = String(value || "")
    .trim()
    .replace(/\/+$/, "");
  return url.length <= 200 && HUB_URL_RE.test(url) ? url : null;
}
class HubError extends Error {
  constructor(status, message, code = "") {
    super(message);
    this.status = status;
    this.code = code;
  }
}
function createHubClient({ fetchImpl, baseURL, token = "" }) {
  const base = normalizeHubURL(baseURL);
  if (!base) throw new Error("Hub URL must be http(s)://host[:port]");
  const mutationListeners = new Set();
  async function request(path, { method = "GET", body, timeoutMs } = {}) {
    const init = { method, headers: {}, timeoutMs };
    if (token) init.headers.Authorization = "Bearer " + token;
    if (body !== undefined) {
      init.body = JSON.stringify(body);
      init.headers["Content-Type"] = "application/json";
    }
    const res = await fetchImpl(base + path, init);
    const text = await res.text();
    let data = null;
    if (text) {
      try {
        data = JSON.parse(text);
      } catch {
        data = null;
      }
    }
    if (res.status >= 400)
      throw new HubError(
        res.status,
        data?.error || res.statusText || "hub error",
        data?.code || "",
      );
    if (method !== "GET")
      for (const listener of mutationListeners) {
        try {
          listener();
        } catch {
          /* A view cannot undo a confirmed write. */
        }
      }
    return data;
  }
  const q = (params) => {
    const s = new URLSearchParams();
    for (const [k, v] of Object.entries(params))
      if (v !== undefined && v !== null && v !== "") s.set(k, String(v));
    const out = s.toString();
    return out ? "?" + out : "";
  };
  const client = {
    base,
    token,
    request,
    onMutation(listener) {
      mutationListeners.add(listener);
      return () => mutationListeners.delete(listener);
    },
    whoami: () => request("/v1/whoami"),
    capabilities: () => request("/v1/capabilities"),
    listTasks: async () => (await request("/v1/tasks")).tasks,
    createTask: (body) => request("/v1/tasks", { method: "POST", body }),
    getTask: (id) => request(`/v1/tasks/${id}`),
    updateTask: (id, body) =>
      request(`/v1/tasks/${id}`, { method: "PATCH", body }),
    closeTask: (id) => request(`/v1/tasks/${id}`, { method: "DELETE" }),
    getTaskPause: (id) => request(`/v1/tasks/${id}/pause`),
    pauseTask: (id, body) =>
      request(`/v1/tasks/${id}/pause`, { method: "POST", body }),
    resolvePauseHandoff: (id, body) =>
      request(`/v1/tasks/${id}/pause/handoff`, { method: "POST", body }),
    resumeTask: (id, body) =>
      request(`/v1/tasks/${id}/resume`, { method: "POST", body }),
    listWorkItems: (params = {}) => request("/v1/work-items" + q(params)),
    getWorkItem: (task, id) => request(`/v1/tasks/${task}/work-items/${id}`),
    createWorkItem: (task, body) =>
      request(`/v1/tasks/${task}/work-items`, { method: "POST", body }),
    updateWorkItem: (task, id, body) =>
      request(`/v1/tasks/${task}/work-items/${id}`, { method: "PATCH", body }),
    createWorkItemUpdate: (task, id, body) =>
      request(`/v1/tasks/${task}/work-items/${id}/updates`, {
        method: "POST",
        body,
      }),
    getWorkItemUpdateReceipt: (task, id, requestId, agentId = "") =>
      request(
        `/v1/tasks/${task}/work-items/${id}/updates/receipts/${encodeURIComponent(requestId)}` +
          q({ agentId }),
      ),
    listWorkItemRevisions: (task, id, params = {}) =>
      request(`/v1/tasks/${task}/work-items/${id}/revisions` + q(params)),
    getWorkItemRevision: (task, id, revision) =>
      request(`/v1/tasks/${task}/work-items/${id}/revisions/${revision}`),
    getWorkOrderScopeConfirmation: (task, id, revision, order) =>
      request(`/v1/tasks/${task}/work-items/${id}/order-scope` + q({ revision, order })),
    listWorkItemHistoryGaps: (task, id, params = {}) =>
      request(`/v1/tasks/${task}/work-items/${id}/history-gaps` + q(params)),
    listWorkItemMessages: (task, id, params = {}) =>
      request(`/v1/tasks/${task}/work-items/${id}/messages` + q(params)),
    getNarrativeOverview: (task, id, params = {}) =>
      request(`/v1/tasks/${task}/work-items/${id}/narrative` + q(params)),
    listNarrativeTimeline: (task, id, params = {}) =>
      request(
        `/v1/tasks/${task}/work-items/${id}/narrative/timeline` + q(params),
      ),
    listNarrativeArtifacts: (task, id, params = {}) =>
      request(
        `/v1/tasks/${task}/work-items/${id}/narrative/artifacts` + q(params),
      ),
    listNarrativeArtifactVersions: (task, id, artifact, params = {}) =>
      request(
        `/v1/tasks/${task}/work-items/${id}/narrative/artifacts/${encodeURIComponent(artifact)}/versions` +
          q(params),
      ),
    getNarrativeArtifactVersion: (task, id, artifact, version) =>
      request(
        `/v1/tasks/${task}/work-items/${id}/narrative/artifacts/${encodeURIComponent(artifact)}/versions/${version}`,
      ),
    putNarrativeArtifact: (task, id, body) =>
      request(`/v1/tasks/${task}/work-items/${id}/narrative/artifacts`, {
        method: "POST",
        body,
      }),
    listNarrativeLinks: (task, id, params = {}) =>
      request(`/v1/tasks/${task}/work-items/${id}/narrative/links` + q(params)),
    putNarrativeLink: (task, id, body) =>
      request(`/v1/tasks/${task}/work-items/${id}/narrative/links`, {
        method: "POST",
        body,
      }),
    listNarrativeCoverage: (task, id, params = {}) =>
      request(
        `/v1/tasks/${task}/work-items/${id}/narrative/coverage` + q(params),
      ),
    putNarrativeCoverage: (task, id, body) =>
      request(`/v1/tasks/${task}/work-items/${id}/narrative/coverage`, {
        method: "POST",
        body,
      }),
    listNarrativeReports: (task, id, params = {}) =>
      request(
        `/v1/tasks/${task}/work-items/${id}/narrative/reports` + q(params),
      ),
    getNarrativeReportVersion: (task, id, report, version) =>
      request(
        `/v1/tasks/${task}/work-items/${id}/narrative/reports/${encodeURIComponent(report)}/versions/${version}`,
      ),
    putNarrativeReport: (task, id, body) =>
      request(`/v1/tasks/${task}/work-items/${id}/narrative/reports`, {
        method: "POST",
        body,
      }),
    getNarrativeReceipt: (task, id, requestId, params = {}) =>
      request(
        `/v1/tasks/${task}/work-items/${id}/narrative/receipts/${encodeURIComponent(requestId)}` +
          q(params),
      ),
    dispatchWorkItem: (task, id, body) =>
      request(`/v1/tasks/${task}/work-items/${id}/dispatch`, {
        method: "POST",
        body,
      }),
    listQueue: (task, params = {}) =>
      request(`/v1/tasks/${task}/queue` + q(params)),
    getQueueEntry: (task, entry) =>
      request(`/v1/tasks/${task}/queue/${encodeURIComponent(entry)}`),
    listQueueHistory: (task, entry, params = {}) =>
      request(
        `/v1/tasks/${task}/queue/${encodeURIComponent(entry)}/history` +
          q(params),
      ),
    listQueueChanges: (task, params = {}) =>
      request(`/v1/tasks/${task}/queue/changes` + q(params)),
    queueAction: (task, entry, body) =>
      request(`/v1/tasks/${task}/queue/${encodeURIComponent(entry)}/actions`, {
        method: "POST",
        body,
      }),
    getQueueReceipt: (task, requestId, agentId = "") =>
      request(
        `/v1/tasks/${task}/queue-receipts/${encodeURIComponent(requestId)}` +
          q({ agentId }),
      ),
    assignLead: (task, body) =>
      request(`/v1/tasks/${task}/lead`, { method: "POST", body }),
    addAgent: (task, body) =>
      request(`/v1/tasks/${task}/agents`, { method: "POST", body }),
    listAgents: async (task) =>
      (await request(`/v1/tasks/${task}/agents`)).agents,
    getAgent: (task, agent) => request(`/v1/tasks/${task}/agents/${agent}`),
    getAgentWorkContext: (task, agent, runId) =>
      request(`/v1/tasks/${task}/agents/${agent}/work-context` + q({ runId })),
    updateAgent: (task, agent, body) =>
      request(`/v1/tasks/${task}/agents/${agent}`, { method: "PATCH", body }),
    closeAgent: (task, agent, runId) =>
      request(`/v1/tasks/${task}/agents/${agent}` + q({ runId }), {
        method: "DELETE",
      }),
    postMessage: (task, body) =>
      request(`/v1/tasks/${task}/messages`, { method: "POST", body }),
    getMessagePostReceipt: (task, requestId, agentId = "") =>
      request(
        `/v1/tasks/${task}/messages/receipts/${encodeURIComponent(requestId)}` +
          q({ agentId }),
      ),
    getMessageAudit: (task, seq) =>
      request(`/v1/tasks/${task}/message-audit/messages/${seq}`),
    listMessageAuditHistory: (task, seq, params = {}) =>
      request(
        `/v1/tasks/${task}/message-audit/messages/${seq}/history` + q(params),
      ),
    listMessageAuditChanges: (task, params = {}) =>
      request(`/v1/tasks/${task}/message-audit/changes` + q(params)),
    correctMessageAudit: (task, seq, body) =>
      request(`/v1/tasks/${task}/message-audit/messages/${seq}/corrections`, {
        method: "POST",
        body,
      }),
    resolveMessageAudit: (task, seq, body) =>
      request(`/v1/tasks/${task}/message-audit/messages/${seq}/resolve`, {
        method: "POST",
        body,
      }),
    getMessageAuditReceipt: (task, requestId, params = {}) =>
      request(
        `/v1/tasks/${task}/message-audit/receipts/${encodeURIComponent(requestId)}` +
          q(params),
      ),
    createMessageAuditAssociation: (task, body) =>
      request(`/v1/tasks/${task}/message-audit/associations`, {
        method: "POST",
        body,
      }),
    getMessageAuditAssociationReceipt: (task, requestId, agentId = "") =>
      request(
        `/v1/tasks/${task}/message-audit/associations/receipts/${encodeURIComponent(requestId)}` +
          q({ agentId }),
      ),
    createAuditExport: (task, body) =>
      request(`/v1/tasks/${task}/audit-exports`, { method: "POST", body }),
    getAuditExportChunk: (task, exportId, params = {}) =>
      request(
        `/v1/tasks/${task}/audit-exports/${encodeURIComponent(exportId)}` +
          q(params),
      ),
    listMessages: async (task, params = {}) =>
      (await request(`/v1/tasks/${task}/messages` + q(params))).messages,
    listDecisions: (task, params = {}) =>
      request(`/v1/tasks/${task}/decisions` + q(params)),
    answerDecision: (task, seq, body) =>
      request(`/v1/tasks/${task}/decisions/${seq}/answer`, {
        method: "POST",
        body,
      }),
    markRead: (task, body) =>
      request(`/v1/tasks/${task}/messages/read`, { method: "POST", body }),
    postEvent: (task, body) =>
      request(`/v1/tasks/${task}/events`, { method: "POST", body }),
    events: (task, { after = 0, wait, limit } = {}) =>
      request(
        (task ? `/v1/tasks/${task}/events` : "/v1/events") +
          q({ after, wait, limit }),
        {
          timeoutMs: wait ? 40000 : undefined,
        },
      ),
    // subscribe long-polls a feed until stop() is called. onEvents receives
    // each non-empty batch; onError receives failures (the loop backs off).
    subscribe(task, onEvents, { after = 0, onError = () => {} } = {}) {
      let stopped = false,
        cursor = after,
        backoff = 1000,
        timer = null;
      const sleep = (ms) =>
        new Promise((resolve) => {
          timer = setTimeout(resolve, ms);
        });
      (async () => {
        while (!stopped) {
          try {
            const list = await client.events(task, {
              after: cursor,
              wait: "25s",
              limit: 100,
            });
            if (stopped) return;
            backoff = 1000;
            if (list.events.length) {
              cursor = list.next;
              try {
                await onEvents(list.events, cursor);
              } catch (error) {
                onError(error);
              }
            }
          } catch (error) {
            if (stopped) return;
            onError(error);
            await sleep(backoff);
            backoff = Math.min(backoff * 2, 30000);
          }
        }
      })();
      return {
        stop() {
          stopped = true;
          clearTimeout(timer);
        },
        cursor: () => cursor,
      };
    },
  };
  return client;
}

async function main() {
  let raw = "";
  for await (const chunk of process.stdin) raw += chunk;
  const input = JSON.parse(raw);
  const client = createHubClient({ baseURL: input.hub, token: input.token,
    fetchImpl: (url, init) => fetch(url, init) });
  if (input.action === "set-orchestrator") {
    process.stdout.write(JSON.stringify(await client.updateTask(input.task,
      { orchestrator: input.orchestrator })) + "\n");
    return;
  }
  const itemRouting = { workItemTaskId: input.task, workItemId: input.item,
    workItemRevision: input.revision, workOrderTaskId: input.task,
    workOrderMessageSeq: input.order };
  itemRouting.workContextBundle = input.workContextBundle ||
    await prepareWorkItemContext(client, {
      itemTaskId: input.task, itemId: input.item, itemRevision: input.revision,
      workOrderMessage: { taskId: input.task, seq: input.order },
    });
  const plan = teamLaunchPlan({ team: exampleTeam(input.template),
    servers: [{ id: "local", name: input.host }], mainServerId: "local",
    projectFolders: { local: input.cwd }, itemRouting,
    handler: input.handler });
  process.stdout.write(JSON.stringify({ plan, itemRouting }) + "\n");
}
main().catch((error) => { console.error(error.message); process.exitCode = 1; });
