package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/scs32/tailterm/hub/internal/api"
)

// Session handoff, stage A (feature wi_3dae763822d9c061). A small structured
// record of what the owner helper session is holding is kept on this host,
// written by `tt handoff note` and `tt handoff write` and stamped by the
// `tt hook handoff` settings hook at session end and compaction. At session
// start the hook prints a bounded note that Claude Code adds to the session's
// context. See docs/session-handoff.md.
//
// Three rules shape everything here:
//
//   - Off unless ~/.config/tailterm/handoff.json holds {"sessionHandoff":"on"}.
//   - The hook never asks the hub, never fails and never writes on PreCompact
//     or SessionEnd, so it cannot block or change a session.
//   - Every stored value is generated by tt or is a validated id, number,
//     time, schedule or fixed-list value. No field accepts words.
//
// Nothing here registers a helper, tags a tmux session, writes a relay
// binding or creates a wake; that is stage B.

func init() { hookHandlers["handoff"] = handoffHook }

// Variables rather than constants so tests can change them.
var (
	handoffDeadline              = 400 * time.Millisecond // the hook's whole wait
	handoffHookLockWait          = 50 * time.Millisecond
	handoffCommandLockWait       = 2 * time.Second
	handoffMaxBytes              = 64 << 10 // largest record.json
	handoffCaptureMax      int64 = 1 << 20  // captures.jsonl size that rotates
	handoffNow                   = time.Now
	// handoffAccessHook sees every path this file opens, lists, creates or
	// renames. Tests use it to fail on a path outside their temporary root.
	handoffAccessHook func(path string)
)

const (
	handoffMaxInput     = 64 << 10 // stdin bytes the hook reads
	handoffListCap      = 50       // entries per note list, rows per snapshot list
	handoffNoteBytes    = 8192     // largest injected note
	handoffHeaderBytes  = 600
	handoffFooterBytes  = 800
	handoffLineBytes    = 120
	handoffLockRetry    = 2 * time.Millisecond
	handoffTimeLayout   = "2006-01-02T15:04:05Z"
	handoffNone         = "none"
	handoffOther        = "other"
	handoffSettingKey   = "sessionHandoff"
	handoffLateLine     = "Tailterm handoff: not read in time; run `tt handoff show`\n"
	handoffBrokenLine   = "Tailterm handoff: the record could not be read; run `tt handoff show`\n"
	handoffNarrative    = ".build/owner-session-handoff.md"
	handoffAsRegistered = "registered"
	handoffAsCandidate  = "candidate"
)

const handoffUsage = "usage: tt handoff show [--task T] [--json]\n" +
	"       tt handoff write --task T [--out PATH]\n" +
	"       tt handoff note wake add --schedule 'M H D M W' --kind K --message N [--expires TIME|DURATION|none]\n" +
	"       tt handoff note instruction add --message N --by owner|delegate [--given TIME] [--expires TIME|DURATION|none]\n" +
	"       tt handoff note order add --item wi_ID --revision N --order N --last STEP --next STEP [--message N]\n" +
	"       tt handoff note decision add --message N --authority owner|delegated|helper\n" +
	"       tt handoff note claim add --message N\n" +
	"       tt handoff note KIND set ID [the same flags]\n" +
	"       tt handoff note KIND close ID [--state S] [--check N]\n" +
	"       every note command also takes --task T"

// ---- the setting ----

func handoffConfigPath() string {
	if path := os.Getenv("TAILTERM_HANDOFF_CONFIG"); path != "" {
		return path
	}
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return ""
	}
	return filepath.Join(home, ".config", "tailterm", "handoff.json")
}

// handoffOn reads the host setting at each use. A missing or unreadable file,
// malformed JSON, a missing key and any value other than the exact string
// "on" mean off. The key is read by its exact name from a map: encoding/json
// would match a struct field without regard to case.
func handoffOn() bool {
	path := handoffConfigPath()
	if path == "" {
		return false
	}
	handoffTouch(path)
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	data, err := io.ReadAll(io.LimitReader(f, 64<<10+1))
	if err != nil || len(data) > 64<<10 {
		return false
	}
	var config map[string]json.RawMessage
	var value string
	return json.Unmarshal(data, &config) == nil && json.Unmarshal(config[handoffSettingKey], &value) == nil && value == "on"
}

func handoffOffError() error {
	return fmt.Errorf("session handoff is off on this host: set %q to \"on\" in %s", handoffSettingKey, handoffConfigPath())
}

// handoffTouch reports a path before this file opens, lists, creates or
// renames it. TAILTERM_HANDOFF_ACCESS_LOG names a file that receives one path
// per line; the live check uses it to prove where the hook reached.
func handoffTouch(path string) {
	if handoffAccessHook != nil {
		handoffAccessHook(path)
	}
	log := os.Getenv("TAILTERM_HANDOFF_ACCESS_LOG")
	if log == "" {
		return
	}
	if f, err := os.OpenFile(log, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600); err == nil {
		_, _ = f.WriteString(path + "\n")
		_ = f.Close()
	}
}

// ---- the record ----

func handoffRoot() string {
	if path := os.Getenv("TAILTERM_HANDOFF_DIR"); path != "" {
		return path
	}
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return ""
	}
	return filepath.Join(home, ".local", "state", "tailterm", "handoff")
}

type handoffRecord struct {
	V        int              `json:"v"`
	Identity handoffIdentity  `json:"identity"`
	Capture  handoffCapture   `json:"capture"`
	Snapshot *handoffSnapshot `json:"snapshot,omitempty"`
	Notes    handoffNotes     `json:"notes"`
}

// handoffIdentity is a copy of the host helper file's identity fields. It
// says what that file said at CopiedAt; it never proves a registration.
type handoffIdentity struct {
	Hub            string `json:"hub"`
	Task           string `json:"task"`
	Agent          string `json:"agent"`
	Name           string `json:"name,omitempty"`
	Run            string `json:"run"`
	Registration   string `json:"registration,omitempty"`
	Runtime        string `json:"runtime,omitempty"`
	Thread         string `json:"thread,omitempty"`
	Session        string `json:"session,omitempty"`
	SessionID      string `json:"sessionId,omitempty"`
	SessionCreated string `json:"sessionCreated,omitempty"`
	CopiedAt       string `json:"copiedAt"`
}

// handoffStamp is one hook event: when, its source, trigger or reason, and
// the Claude Code session id.
type handoffStamp struct {
	Time    string `json:"time"`
	Detail  string `json:"detail"`
	Session string `json:"session,omitempty"`
}

type handoffCapture struct {
	Start   *handoffStamp `json:"start,omitempty"`
	Compact *handoffStamp `json:"compact,omitempty"`
	End     *handoffStamp `json:"end,omitempty"`
}

// handoffSnapshot is what the hub said at AsOf. It is a dated copy for a
// runtime switch, never authority: the hub is read again before acting.
type handoffSnapshot struct {
	AsOf               string              `json:"asOf"`
	HelperStatus       string              `json:"helperStatus"`
	Window             *handoffWindow      `json:"window,omitempty"`
	Obligations        []handoffObligation `json:"obligations"`
	ObligationsOmitted int                 `json:"obligationsOmitted"`
	Decisions          []handoffDecision   `json:"decisions"`
	DecisionsOmitted   int                 `json:"decisionsOmitted"`
	Queue              []handoffQueueRow   `json:"queue"`
	QueueOmitted       int                 `json:"queueOmitted"`
}

type handoffWindow struct {
	ID     string `json:"id"`
	Scope  string `json:"scope"`
	EndsAt string `json:"endsAt"`
	State  string `json:"state"`
}

type handoffObligation struct {
	ID      string `json:"id"`
	Message int64  `json:"message"`
	Kind    string `json:"kind"`
	Sender  string `json:"sender"`
	DueAt   string `json:"dueAt,omitempty"`
	State   string `json:"state"`
}

type handoffDecision struct {
	Message int64  `json:"message"`
	Sender  string `json:"sender"`
	State   string `json:"state"`
}

type handoffQueueRow struct {
	ID       string `json:"id"`
	Item     string `json:"item"`
	Revision int64  `json:"revision"`
	Order    int64  `json:"order"`
	State    string `json:"state"`
}

// handoffEntry is one session note. Which fields a note kind uses is in
// handoffKinds; the rest stay empty.
type handoffEntry struct {
	ID       string `json:"id"`
	State    string `json:"state"`
	Created  string `json:"created"`
	Updated  string `json:"updated"`
	Message  int64  `json:"message,omitempty"`  // the Board message that says what this is
	Schedule string `json:"schedule,omitempty"` // wake: five-field cron
	Kind     string `json:"kind,omitempty"`     // wake
	Expires  string `json:"expires,omitempty"`  // wake, instruction: a time or "none"
	By       string `json:"by,omitempty"`       // instruction: who gave it; decision: authority
	Given    string `json:"given,omitempty"`    // instruction: when
	Item     string `json:"item,omitempty"`     // order
	Revision int64  `json:"revision,omitempty"` // order
	Order    int64  `json:"order,omitempty"`    // order: work-order message
	Last     string `json:"last,omitempty"`     // order: last action
	Next     string `json:"next,omitempty"`     // order: expected next action
	Check    int64  `json:"check,omitempty"`    // claim: the message of the check
}

type handoffList struct {
	Entries []handoffEntry `json:"entries"`
	Next    int            `json:"next"`    // the number of the next entry id; ids are never reused
	Dropped int            `json:"dropped"` // closed entries removed to make room
	Changed string         `json:"changed,omitempty"`
}

type handoffNotes struct {
	Instructions handoffList `json:"instructions"`
	Wakes        handoffList `json:"wakes"`
	Orders       handoffList `json:"orders"`
	Claims       handoffList `json:"claims"`
	Decisions    handoffList `json:"decisions"`
}

// handoffKind describes one note kind: its fields, the fields add requires,
// its opening state and the states close may set (the first is the default).
type handoffKind struct {
	name, plural, prefix string
	list                 func(*handoffNotes) *handoffList
	fields, required     []string
	open                 string
	closed               []string
	checkOnClose         bool
}

// handoffKinds is in the order the injected note and tt handoff show use.
var handoffKinds = []handoffKind{
	{name: "instruction", plural: "instructions", prefix: "i", list: func(n *handoffNotes) *handoffList { return &n.Instructions },
		fields: []string{"message", "by", "given", "expires"}, required: []string{"message", "by"}, open: "active", closed: []string{"revoked"}},
	{name: "wake", plural: "wakes", prefix: "w", list: func(n *handoffNotes) *handoffList { return &n.Wakes },
		fields: []string{"schedule", "kind", "message", "expires"}, required: []string{"schedule", "kind", "message"}, open: "active", closed: []string{"cancelled"}},
	{name: "order", plural: "orders", prefix: "o", list: func(n *handoffNotes) *handoffList { return &n.Orders },
		fields: []string{"item", "revision", "order", "last", "next", "message"}, required: []string{"item", "revision", "order", "last", "next"}, open: "open", closed: []string{"done", "dropped"}},
	{name: "claim", plural: "claims", prefix: "c", list: func(n *handoffNotes) *handoffList { return &n.Claims },
		fields: []string{"message"}, required: []string{"message"}, open: "unverified", closed: []string{"verified", "refuted"}, checkOnClose: true},
	{name: "decision", plural: "decisions", prefix: "d", list: func(n *handoffNotes) *handoffList { return &n.Decisions },
		fields: []string{"message", "authority"}, required: []string{"message", "authority"}, open: "recorded", closed: []string{"closed"}},
}

func handoffKindNamed(name string) (handoffKind, bool) {
	for _, k := range handoffKinds {
		if k.name == name {
			return k, true
		}
	}
	return handoffKind{}, false
}

// The fixed lists. A value outside its list is refused, or stored as "other"
// where the value comes from Claude Code or the hub and not from the session.
var (
	handoffWakeKinds     = []string{"hourly-update", "morning-summary", "queue-check", "obligation-check", "authority-expiry", handoffOther}
	handoffGivers        = []string{"owner", "delegate"}
	handoffAuthorities   = []string{"owner", "delegated", "helper"}
	handoffOrderSteps    = []string{"send-order", "await-start", "await-result", "review", "verify", "release", "answer-owner", handoffOther}
	handoffRuntimes      = []string{"claude", "codex"}
	handoffStartSources  = []string{"startup", "resume", "clear", "compact", "fork"}
	handoffTriggers      = []string{"manual", "auto"}
	handoffEndReasons    = []string{"clear", "resume", "logout", "prompt_input_exit"}
	handoffAgentStatuses = []string{api.AgentStarting, api.AgentRunning, api.AgentDone, api.AgentRetired, api.AgentNeedsInput, api.AgentClosed, api.AgentExited}
	handoffWindowScopes  = []string{api.DelegationScopeDecisions, api.DelegationScopeDecisionsMergesDeploys}
	handoffWindowStates  = []string{api.DelegationOpen, api.DelegationExpired, api.DelegationClosed}
	handoffObligKinds    = []string{"assign", "request", "review", "question", "block", "notice", "finding", "result", "answer", "decline", "human", "decision"}
	handoffObligStates   = []string{api.ObligationQueued, api.ObligationDelivered, api.ObligationAcknowledged, api.ObligationWorking, api.ObligationBlocked, api.ObligationClosed}
	handoffQueueStates   = []string{"launching", "running"}
	handoffSenderWords   = []string{"human", "unknown"}
)

var (
	handoffMessagePattern  = regexp.MustCompile(`^[1-9][0-9]{0,11}$`)
	handoffRevisionPattern = regexp.MustCompile(`^[1-9][0-9]{0,8}$`)
	handoffEntryIDPattern  = regexp.MustCompile(`^[iwocd][1-9][0-9]{0,8}$`)
	handoffHexIDPattern    = regexp.MustCompile(`^[a-z]{2,5}_[0-9a-f]{16}$`)
	handoffHubPattern      = regexp.MustCompile(`^https?://[A-Za-z0-9.-]{1,253}(:[0-9]{1,5})?$`)
	handoffTimePattern     = regexp.MustCompile(`^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$`)
)

func handoffIn(value string, list []string) bool {
	for _, v := range list {
		if v == value {
			return true
		}
	}
	return false
}

// handoffListed is value when the list holds it and "other" otherwise. It is
// for values tt did not choose: Claude Code's and the hub's.
func handoffListed(value string, list []string) string {
	if handoffIn(value, list) {
		return value
	}
	return handoffOther
}

func handoffID(value, prefix string) bool {
	return handoffHexIDPattern.MatchString(value) && strings.HasPrefix(value, prefix+"_")
}

func handoffStamped(t time.Time) string { return t.UTC().Format(handoffTimeLayout) }

func handoffTimeOK(value string) bool {
	if !handoffTimePattern.MatchString(value) {
		return false
	}
	_, err := time.Parse(handoffTimeLayout, value)
	return err == nil
}

// handoffParseTime accepts an RFC 3339 time and stores it in UTC to the
// second. Nothing else is a time.
func handoffParseTime(value string) (string, error) {
	t, err := time.Parse(time.RFC3339, value)
	if err != nil || len(value) > 40 || t.Year() < 2000 || t.Year() > 9999 {
		return "", errors.New("is not an RFC 3339 time, such as 2026-10-08T04:00:00Z")
	}
	return handoffStamped(t), nil
}

// handoffParseExpiry accepts a time, "none", or a duration from now.
func handoffParseExpiry(value string) (string, error) {
	if value == handoffNone {
		return handoffNone, nil
	}
	if len(value) <= 16 {
		if d, err := time.ParseDuration(value); err == nil {
			if d <= 0 || d > 366*24*time.Hour {
				return "", errors.New("is not a duration between 1s and 8784h")
			}
			return handoffStamped(handoffNow().Add(d)), nil
		}
	}
	if stamp, err := handoffParseTime(value); err == nil {
		return stamp, nil
	}
	return "", errors.New("is not an RFC 3339 time, a duration such as 12h, or none")
}

// handoffParseSchedule accepts a five-field cron schedule whose fields are
// numbers, ranges, lists and steps inside each field's range, and stores it
// with single spaces. Names such as MON are refused: a schedule holds no
// letters.
func handoffParseSchedule(value string) (string, error) {
	bad := errors.New("is not a five-field cron schedule of numbers, ranges, lists and steps within range, such as '0 * * * *'")
	if len(value) > 64 {
		return "", bad
	}
	fields := strings.Fields(value)
	if len(fields) != 5 {
		return "", bad
	}
	for i, r := range [5][2]int{{0, 59}, {0, 23}, {1, 31}, {1, 12}, {0, 7}} {
		for _, part := range strings.Split(fields[i], ",") {
			base, step, stepped := strings.Cut(part, "/")
			if stepped {
				if n, ok := handoffCronNumber(step); !ok || n < 1 || n > r[1] {
					return "", bad
				}
			}
			if base == "*" {
				continue
			}
			low, high, ranged := strings.Cut(base, "-")
			a, ok := handoffCronNumber(low)
			if !ok || a < r[0] || a > r[1] {
				return "", bad
			}
			if ranged {
				if b, ok := handoffCronNumber(high); !ok || b < a || b > r[1] {
					return "", bad
				}
			}
		}
	}
	return strings.Join(fields, " "), nil
}

func handoffCronNumber(s string) (int, bool) {
	if len(s) == 0 || len(s) > 2 {
		return 0, false
	}
	for i := 0; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return 0, false
		}
	}
	n, err := strconv.Atoi(s)
	return n, err == nil
}

// handoffSetField validates one note field and stores it. The value is
// refused unless it is exactly one of the validated kinds; nothing is cut,
// trimmed or otherwise repaired into shape.
func handoffSetField(k handoffKind, entry *handoffEntry, field, value string) error {
	fail := func(reason string) error { return fmt.Errorf("--%s %s", field, reason) }
	number := func(pattern *regexp.Regexp, what string) (int64, error) {
		if !pattern.MatchString(value) {
			return 0, fail("is not " + what)
		}
		return strconv.ParseInt(value, 10, 64)
	}
	listed := func(list []string) error {
		if !handoffIn(value, list) {
			return fail("is not one of: " + strings.Join(list, ", "))
		}
		return nil
	}
	const message = "a Board message number (1 to 12 digits)"
	var err error
	switch field {
	case "message":
		entry.Message, err = number(handoffMessagePattern, message)
	case "order":
		entry.Order, err = number(handoffMessagePattern, message)
	case "check":
		entry.Check, err = number(handoffMessagePattern, message)
	case "revision":
		entry.Revision, err = number(handoffRevisionPattern, "a revision number (1 to 9 digits)")
	case "item":
		if !api.ValidID(value, "wi") {
			return fail("is not a work-item id (wi_ and 16 hex digits)")
		}
		entry.Item = value
	case "schedule":
		if entry.Schedule, err = handoffParseSchedule(value); err != nil {
			return fail(err.Error())
		}
	case "kind":
		if err = listed(handoffWakeKinds); err == nil {
			entry.Kind = value
		}
	case "by":
		if err = listed(handoffGivers); err == nil {
			entry.By = value
		}
	case "authority":
		if err = listed(handoffAuthorities); err == nil {
			entry.By = value
		}
	case "last":
		if err = listed(handoffOrderSteps); err == nil {
			entry.Last = value
		}
	case "next":
		if err = listed(handoffOrderSteps); err == nil {
			entry.Next = value
		}
	case "given":
		if entry.Given, err = handoffParseTime(value); err != nil {
			return fail(err.Error())
		}
	case "expires":
		if entry.Expires, err = handoffParseExpiry(value); err != nil {
			return fail(err.Error())
		}
	default:
		return fmt.Errorf("a %s note has no --%s", k.name, field)
	}
	return err
}

// handoffEntryState is the state shown for an entry at now: an active entry
// past its expiry is expired without anything having run.
func handoffEntryState(entry handoffEntry, now time.Time) string {
	if entry.State == "active" && entry.Expires != "" && entry.Expires != handoffNone {
		if t, err := time.Parse(handoffTimeLayout, entry.Expires); err == nil && !now.Before(t) {
			return "expired"
		}
	}
	return entry.State
}

// handoffLive reports a state that still asks something of the session.
func handoffLive(state string) bool {
	return state == "active" || state == "open" || state == "unverified" || state == "recorded"
}

// valid reports whether every value in the record is one tt could have
// written. A record that fails is never printed or injected: a hand-edited
// file must not put words into a session's context.
func (r handoffRecord) valid() bool {
	id := r.Identity
	if r.V != 1 || !handoffHubPattern.MatchString(id.Hub) || !api.ValidID(id.Task, "tsk") || !api.ValidID(id.Agent, "agt") || !handoffTimeOK(id.CopiedAt) ||
		!handoffID(id.Run, "run") || id.Name != "" && !api.ValidName(id.Name) || id.Registration != "" && !handoffID(id.Registration, "ohr") ||
		id.Runtime != "" && !handoffIn(id.Runtime, handoffRuntimes) || id.Thread != "" && !threadIDPattern.MatchString(id.Thread) ||
		id.Session != "" && !api.ValidName(id.Session) || id.SessionID != "" && !sessionIDPattern.MatchString(id.SessionID) || len(id.SessionID) > 12 ||
		id.SessionCreated != "" && !sessionTimePattern.MatchString(id.SessionCreated) || len(id.SessionCreated) > 12 {
		return false
	}
	for _, c := range []struct {
		stamp *handoffStamp
		list  []string
	}{{r.Capture.Start, handoffStartSources}, {r.Capture.Compact, handoffTriggers}, {r.Capture.End, handoffEndReasons}} {
		if s := c.stamp; s != nil && (!handoffTimeOK(s.Time) || s.Detail != handoffOther && !handoffIn(s.Detail, c.list) || s.Session != "" && !threadIDPattern.MatchString(s.Session)) {
			return false
		}
	}
	if s := r.Snapshot; s != nil {
		if !handoffTimeOK(s.AsOf) || s.HelperStatus != handoffOther && !handoffIn(s.HelperStatus, handoffAgentStatuses) ||
			len(s.Obligations) > handoffListCap || len(s.Decisions) > handoffListCap || len(s.Queue) > handoffListCap ||
			s.ObligationsOmitted < 0 || s.DecisionsOmitted < 0 || s.QueueOmitted < 0 {
			return false
		}
		if w := s.Window; w != nil && (!handoffID(w.ID, "dlw") || !handoffIn(w.Scope, append([]string{handoffOther}, handoffWindowScopes...)) || !handoffTimeOK(w.EndsAt) || !handoffIn(w.State, handoffWindowStates)) {
			return false
		}
		sender := func(s string) bool { return api.ValidID(s, "agt") || handoffIn(s, handoffSenderWords) }
		for _, o := range s.Obligations {
			if !handoffID(o.ID, "obl") || o.Message < 1 || !handoffIn(o.Kind, append([]string{handoffOther}, handoffObligKinds...)) || !sender(o.Sender) ||
				o.DueAt != "" && !handoffTimeOK(o.DueAt) || !handoffIn(o.State, append([]string{handoffOther}, handoffObligStates...)) {
				return false
			}
		}
		for _, d := range s.Decisions {
			if d.Message < 1 || !sender(d.Sender) || d.State != "open" {
				return false
			}
		}
		for _, q := range s.Queue {
			if !handoffID(q.ID, "tqe") || !api.ValidID(q.Item, "wi") || q.Revision < 1 || q.Order < 0 || !handoffIn(q.State, handoffQueueStates) {
				return false
			}
		}
	}
	for _, k := range handoffKinds {
		list := k.list(&r.Notes)
		if len(list.Entries) > handoffListCap || list.Next < 0 || list.Dropped < 0 || list.Changed != "" && !handoffTimeOK(list.Changed) {
			return false
		}
		for _, entry := range list.Entries {
			if !handoffEntryValid(k, entry) {
				return false
			}
		}
	}
	return true
}

func handoffEntryValid(k handoffKind, e handoffEntry) bool {
	if !handoffEntryIDPattern.MatchString(e.ID) || !strings.HasPrefix(e.ID, k.prefix) || !handoffTimeOK(e.Created) || !handoffTimeOK(e.Updated) ||
		e.State != k.open && !handoffIn(e.State, k.closed) || e.Message < 0 || e.Order < 0 || e.Check < 0 || e.Revision < 0 {
		return false
	}
	// Every field the kind does not use must be empty, and every one it uses
	// must hold a validated value.
	want := handoffEntry{ID: e.ID, State: e.State, Created: e.Created, Updated: e.Updated, Message: e.Message}
	uses := func(field string) bool { return handoffIn(field, k.fields) }
	if uses("schedule") {
		if s, err := handoffParseSchedule(e.Schedule); err != nil || s != e.Schedule || !handoffIn(e.Kind, handoffWakeKinds) {
			return false
		}
		want.Schedule, want.Kind = e.Schedule, e.Kind
	}
	if uses("expires") {
		if e.Expires != handoffNone && !handoffTimeOK(e.Expires) {
			return false
		}
		want.Expires = e.Expires
	}
	if uses("by") && !handoffIn(e.By, handoffGivers) || uses("authority") && !handoffIn(e.By, handoffAuthorities) {
		return false
	}
	if uses("by") || uses("authority") {
		want.By = e.By
	}
	if uses("given") {
		if !handoffTimeOK(e.Given) {
			return false
		}
		want.Given = e.Given
	}
	if uses("item") {
		if !api.ValidID(e.Item, "wi") || e.Revision < 1 || e.Order < 1 || !handoffIn(e.Last, handoffOrderSteps) || !handoffIn(e.Next, handoffOrderSteps) {
			return false
		}
		want.Item, want.Revision, want.Order, want.Last, want.Next = e.Item, e.Revision, e.Order, e.Last, e.Next
	} else if e.Message < 1 {
		return false
	}
	if k.checkOnClose {
		want.Check = e.Check
	}
	return e == want
}

// handoffStore is one agent's record directory.
type handoffStore struct {
	dir      string
	lockWait time.Duration
}

func handoffStoreFor(agent string, lockWait time.Duration) (handoffStore, bool) {
	root := handoffRoot()
	if root == "" || !api.ValidID(agent, "agt") {
		return handoffStore{}, false
	}
	return handoffStore{dir: filepath.Join(root, agent), lockWait: lockWait}, true
}

func (s handoffStore) path(name string) string { return filepath.Join(s.dir, name) }

// prepare creates the record directory, private to the user.
func (s handoffStore) prepare() error {
	root := filepath.Dir(s.dir)
	for _, dir := range []string{root, s.dir} {
		handoffTouch(dir)
		if err := os.MkdirAll(dir, 0700); err != nil {
			return err
		}
		if err := os.Chmod(dir, 0700); err != nil {
			return err
		}
	}
	return nil
}

// lock returns the unlock function, or nil when the lock was not obtained in
// time. The lock ends with the process, so a killed hook leaves none behind.
func (s handoffStore) lock() func() {
	path := s.path("handoff.lock")
	handoffTouch(path)
	f, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR, 0600)
	if err != nil {
		return nil
	}
	for waited := time.Duration(0); ; waited += handoffLockRetry {
		err = syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB)
		if err == nil {
			return func() { _ = syscall.Flock(int(f.Fd()), syscall.LOCK_UN); _ = f.Close() }
		}
		if (!errors.Is(err, syscall.EWOULDBLOCK) && !errors.Is(err, syscall.EAGAIN)) || waited >= s.lockWait {
			_ = f.Close()
			return nil
		}
		time.Sleep(handoffLockRetry)
	}
}

var (
	errHandoffNoRecord  = errors.New("no handoff record")
	errHandoffBadRecord = errors.New("the handoff record holds a value tt did not write; move it aside and start again")
)

// load reads record.json and the bytes it was read from.
func (s handoffStore) load() (handoffRecord, []byte, error) {
	path := s.path("record.json")
	handoffTouch(path)
	f, err := os.Open(path)
	if errors.Is(err, os.ErrNotExist) {
		return handoffRecord{}, nil, errHandoffNoRecord
	}
	if err != nil {
		return handoffRecord{}, nil, err
	}
	defer f.Close()
	data, err := io.ReadAll(io.LimitReader(f, int64(handoffMaxBytes)+1))
	if err != nil {
		return handoffRecord{}, nil, err
	}
	var r handoffRecord
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if len(data) > handoffMaxBytes || dec.Decode(&r) != nil || !r.valid() {
		return handoffRecord{}, nil, errHandoffBadRecord
	}
	return r, data, nil
}

// save replaces record.json by write-to-temporary and rename, keeping the
// bytes it replaces as record.json.1. A record over the size bound is
// refused, naming the largest list.
func (s handoffStore) save(r handoffRecord, previous []byte) error {
	for _, k := range handoffKinds {
		if list := k.list(&r.Notes); list.Entries == nil {
			list.Entries = []handoffEntry{} // an empty list is stored as [], never null
		}
	}
	data, err := json.Marshal(r)
	if err != nil {
		return err
	}
	data = append(data, '\n')
	if len(data) > handoffMaxBytes {
		return fmt.Errorf("the record would pass %d bytes; the %s list is full: close or drop entries first", handoffMaxBytes, r.largestList())
	}
	if !r.valid() {
		return errHandoffBadRecord
	}
	path := s.path("record.json")
	if previous != nil {
		if err := s.replace(path+".1", previous); err != nil {
			return err
		}
	}
	return s.replace(path, data)
}

func (s handoffStore) replace(path string, data []byte) error {
	tmp := fmt.Sprintf("%s.tmp-%d", path, os.Getpid())
	handoffTouch(tmp)
	if err := os.WriteFile(tmp, data, 0600); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	handoffTouch(path)
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

func (r handoffRecord) largestList() string {
	name, most := "notes", 0
	size := func(label string, v any) {
		if data, err := json.Marshal(v); err == nil && len(data) > most {
			name, most = label, len(data)
		}
	}
	for _, k := range handoffKinds {
		size(k.plural, k.list(&r.Notes).Entries)
	}
	if r.Snapshot != nil {
		size("snapshot obligations", r.Snapshot.Obligations)
		size("snapshot decisions", r.Snapshot.Decisions)
		size("snapshot queue", r.Snapshot.Queue)
	}
	return name
}

// appendCapture adds one line to captures.jsonl, rotating it at the size
// bound. The caller holds the lock.
func (s handoffStore) appendCapture(event string, stamp handoffStamp, match string) {
	line, err := json.Marshal(struct {
		V       int    `json:"v"`
		Time    string `json:"time"`
		Event   string `json:"event"`
		Detail  string `json:"detail"`
		Session string `json:"session,omitempty"`
		Match   string `json:"match"`
	}{1, stamp.Time, event, stamp.Detail, stamp.Session, match})
	if err != nil {
		return
	}
	path := s.path("captures.jsonl")
	handoffTouch(path)
	if info, err := os.Stat(path); err == nil && info.Size() >= handoffCaptureMax {
		handoffTouch(path + ".1")
		_ = os.Rename(path, path+".1")
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
	if err != nil {
		return
	}
	_, _ = f.Write(append(line, '\n'))
	_ = f.Close()
}

// ---- which helper a session belongs to ----

// handoffHelperFiles reads the host's owner helper files, without the hub.
// It trusts a file only under the name its own hub and task give it and
// gives up past the same bounds as offlineOwnerHelper.
func handoffHelperFiles() ([]ownerHelperFile, bool) {
	dir := relayDir()
	handoffTouch(dir)
	d, err := os.Open(dir)
	if err != nil {
		return nil, false
	}
	defer d.Close()
	var candidates []string
	for {
		names, err := d.Readdirnames(4096) // names only: no stat per entry
		for _, name := range names {
			if !strings.HasSuffix(name, ownerHelperSuffix) {
				continue
			}
			if len(candidates) == ownerHelperCandidates {
				return nil, false
			}
			candidates = append(candidates, name)
		}
		if err != nil {
			if err != io.EOF {
				return nil, false
			}
			break
		}
	}
	sort.Strings(candidates)
	var files []ownerHelperFile
	for _, name := range candidates {
		var f ownerHelperFile
		path := filepath.Join(dir, name)
		handoffTouch(path)
		if readOwnerHelperFile(path, &f) != nil {
			continue
		}
		if name != filepath.Base(ownerHelperPath(f.Hub, f.Task)) || !handoffIdentityOf(f, time.Time{}).usable() {
			continue
		}
		files = append(files, f)
	}
	return files, true
}

// handoffIdentityOf copies the identity fields of a helper file. Its request
// ids and hashes are not copied.
func handoffIdentityOf(f ownerHelperFile, at time.Time) handoffIdentity {
	return handoffIdentity{Hub: f.Hub, Task: f.Task, Agent: f.Agent, Name: f.Name, Run: f.Run, Registration: f.Registration, Runtime: f.Runtime,
		Thread: f.Thread, Session: f.Session, SessionID: f.SessionID, SessionCreated: f.SessionCreated, CopiedAt: handoffStamped(at)}
}

// usable reports a helper file whose identity the record can hold.
func (id handoffIdentity) usable() bool {
	return handoffRecord{V: 1, Identity: id}.valid() && toolLedgerAgentOK(id.Agent)
}

// same compares two identities apart from when they were copied.
func (id handoffIdentity) same(other handoffIdentity) bool {
	other.CopiedAt = id.CopiedAt
	return id == other
}

// handoffMatchThread is the one helper file naming this runtime thread.
func handoffMatchThread(files []ownerHelperFile, runtime, thread string) (ownerHelperFile, bool) {
	var found ownerHelperFile
	matches := 0
	if runtime == "" || !threadIDPattern.MatchString(thread) {
		return found, false
	}
	for _, f := range files {
		if f.Runtime == runtime && f.Thread == thread {
			found = f
			matches++
		}
	}
	return found, matches == 1
}

// handoffMatchTmux is the one helper file whose tmux session, by id and
// creation time, is the session this process's pane is in. It asks tmux at
// most once, and not at all when no helper file names a tmux session.
func handoffMatchTmux(ctx context.Context, files []ownerHelperFile) (ownerHelperFile, bool) {
	pane := os.Getenv("TMUX_PANE")
	named := false
	for _, f := range files {
		named = named || f.SessionID != "" && f.SessionCreated != ""
	}
	if !named || os.Getenv("TMUX") == "" || pane == "" {
		return ownerHelperFile{}, false
	}
	args := []string{"display-message", "-p", "-t", pane, "-F", `["#{q/e:session_id}","#{q/e:session_created}"]`}
	if socket := os.Getenv("TT_TMUX_SOCKET"); socket != "" {
		args = append([]string{"-L", socket}, args...)
	}
	cmd := exec.CommandContext(ctx, "tmux", args...)
	cmd.WaitDelay = 20 * time.Millisecond
	raw, err := cmd.Output()
	var values []string
	if err != nil || json.Unmarshal(bytes.TrimSpace(raw), &values) != nil || len(values) != 2 ||
		!sessionIDPattern.MatchString(values[0]) || !sessionTimePattern.MatchString(values[1]) {
		return ownerHelperFile{}, false
	}
	var found ownerHelperFile
	matches := 0
	for _, f := range files {
		if f.SessionID == values[0] && f.SessionCreated == values[1] {
			found = f
			matches++
		}
	}
	return found, matches == 1
}

// ---- the hook ----

// handoffHookInput holds the only fields decoded from Claude Code's payload.
// cwd, transcript_path and custom_instructions are skipped by the decoder.
type handoffHookInput struct {
	Event   string `json:"hook_event_name"`
	Session string `json:"session_id"`
	Source  string `json:"source"`
	Trigger string `json:"trigger"`
	Reason  string `json:"reason"`
}

// handoffHook runs for SessionStart, PreCompact and SessionEnd. It checks the
// setting first and returns at once when it is off or when the session is a
// Tailterm agent. Otherwise the work, stdin read included, happens in a
// goroutine the handler waits on for at most the deadline. When the handler
// returns, cmdHook returns nil and the process exits 0.
//
// It makes no hub request. Only SessionStart ever prints, and only for the
// helper's own session or a new session in the helper's tmux session.
func handoffHook(e env, _ []string) {
	if !handoffOn() || e.agent != "" {
		return
	}
	run := handoffHookRun{started: time.Now(), deadline: handoffDeadline, in: os.Stdin, out: os.Stdout}
	done := make(chan struct{})
	go func() {
		defer close(done)
		defer func() { _ = recover() }()
		run.work()
	}()
	timer := time.NewTimer(run.deadline)
	defer timer.Stop()
	select {
	case <-done:
	case <-timer.C:
		run.mu.Lock()
		if run.owes {
			_, _ = io.WriteString(run.out, handoffLateLine)
		}
		run.closed = true
		run.mu.Unlock()
	}
}

type handoffHookRun struct {
	started  time.Time
	deadline time.Duration
	in       io.Reader
	out      io.Writer
	mu       sync.Mutex
	owes     bool // a matched SessionStart has not printed yet
	closed   bool // the handler has returned; print nothing more
}

func (h *handoffHookRun) late() bool { return time.Since(h.started) >= h.deadline }

func (h *handoffHookRun) work() {
	data, err := io.ReadAll(io.LimitReader(h.in, handoffMaxInput+1))
	var p handoffHookInput
	if err != nil || h.late() || len(data) > handoffMaxInput || json.Unmarshal(data, &p) != nil {
		return
	}
	var slot func(*handoffCapture) **handoffStamp
	stamp := handoffStamp{Time: handoffStamped(handoffNow())}
	switch p.Event {
	case "SessionStart":
		stamp.Detail, slot = handoffListed(p.Source, handoffStartSources), func(c *handoffCapture) **handoffStamp { return &c.Start }
	case "PreCompact":
		stamp.Detail, slot = handoffListed(p.Trigger, handoffTriggers), func(c *handoffCapture) **handoffStamp { return &c.Compact }
	case "SessionEnd":
		stamp.Detail, slot = handoffListed(p.Reason, handoffEndReasons), func(c *handoffCapture) **handoffStamp { return &c.End }
	default:
		return
	}
	thread := p.Session
	if !threadIDPattern.MatchString(thread) {
		thread = os.Getenv("CLAUDE_CODE_SESSION_ID")
	}
	if threadIDPattern.MatchString(thread) {
		stamp.Session = strings.ToLower(thread)
	}
	files, ok := handoffHelperFiles()
	if !ok || len(files) == 0 {
		return
	}
	ctx, cancel := context.WithDeadline(context.Background(), h.started.Add(h.deadline))
	defer cancel()
	helper, match := ownerHelperFile{}, handoffAsRegistered
	if found, ok := handoffMatchThread(files, "claude", thread); ok {
		helper = found
	} else if found, ok := handoffMatchTmux(ctx, files); ok {
		helper, match = found, handoffAsCandidate
	} else {
		return
	}
	start := p.Event == "SessionStart"
	if start {
		h.mu.Lock()
		h.owes = !h.closed
		h.mu.Unlock()
	}
	if h.late() {
		return
	}
	note := handoffBrokenLine
	if store, ok := handoffStoreFor(helper.Agent, handoffHookLockWait); ok {
		if r, noEnd, err := store.stamp(helper, p.Event, stamp, slot, match, h.late); err == nil {
			note = handoffNote(r, match, noEnd, handoffNow())
		}
	}
	if !start {
		return
	}
	h.mu.Lock()
	if !h.closed {
		_, _ = io.WriteString(h.out, note)
	}
	h.owes = false
	h.mu.Unlock()
}

// stamp records one hook event in the record's capture part and the capture
// log, leaving the notes and the snapshot as they were. It returns the record
// and whether the previous session left no end stamp. A record that cannot
// be written is still returned, so the note is printed from what was read.
func (s handoffStore) stamp(helper ownerHelperFile, event string, stamp handoffStamp, slot func(*handoffCapture) **handoffStamp, match string, late func() bool) (handoffRecord, bool, error) {
	prepared := s.prepare() == nil
	var unlock func()
	if prepared {
		unlock = s.lock()
	}
	if unlock != nil {
		defer unlock()
	}
	r, previous, err := s.load()
	if errors.Is(err, errHandoffNoRecord) {
		r, err = handoffRecord{V: 1}, nil
	}
	if err != nil {
		return handoffRecord{}, false, err
	}
	// A start that follows a start with no end between them means the
	// previous session was killed; a compaction continues the same session.
	noEnd := event == "SessionStart" && stamp.Detail != "compact" && r.Capture.Start != nil &&
		(r.Capture.End == nil || r.Capture.End.Time < r.Capture.Start.Time)
	r.refreshIdentity(helper)
	*slot(&r.Capture) = &stamp
	if unlock == nil || late() {
		return r, noEnd, nil
	}
	if s.save(r, previous) == nil {
		s.appendCapture(event, stamp, match)
	}
	return r, noEnd, nil
}

// refreshIdentity copies the helper file's identity when it differs from the
// record's, and leaves the copy time alone when it does not.
func (r *handoffRecord) refreshIdentity(helper ownerHelperFile) {
	if id := handoffIdentityOf(helper, handoffNow()); !r.Identity.same(id) {
		r.Identity = id
	}
}

// ---- the injected note and tt handoff show ----

// handoffEntryLine is one entry in full, for tt handoff show. It holds ids,
// states, Board message numbers, times and fixed-list values: no words from
// any message.
func handoffEntryLine(k handoffKind, e handoffEntry, now time.Time) string {
	line := fmt.Sprintf("%s %s %s", e.ID, handoffEntryState(e, now), k.name)
	switch k.name {
	case "wake":
		line += fmt.Sprintf(" %s cron %q msg #%d expires %s", e.Kind, e.Schedule, e.Message, e.Expires)
	case "instruction":
		line += fmt.Sprintf(" msg #%d by %s given %s expires %s", e.Message, e.By, e.Given, e.Expires)
	case "order":
		line += fmt.Sprintf(" %s rev %d order #%d last %s next %s", e.Item, e.Revision, e.Order, e.Last, e.Next)
		if e.Message > 0 {
			line += fmt.Sprintf(" msg #%d", e.Message)
		}
	case "decision":
		line += fmt.Sprintf(" msg #%d authority %s", e.Message, e.By)
	case "claim":
		line += fmt.Sprintf(" msg #%d", e.Message)
		if e.Check > 0 {
			line += fmt.Sprintf(" check #%d", e.Check)
		}
	}
	return line
}

// handoffBriefLine is one entry on one line of at most handoffLineBytes, for
// the injected note: the entry id, its state, its kind, its Board message
// number and its expiry. A wake's schedule is added only when it fits; the
// rest of an entry is in tt handoff show.
func handoffBriefLine(k handoffKind, e handoffEntry, now time.Time) string {
	line := fmt.Sprintf("%s %s %s", e.ID, handoffEntryState(e, now), k.name)
	switch k.name {
	case "wake":
		line += fmt.Sprintf(" %s msg #%d expires %s", e.Kind, e.Message, e.Expires)
		if cron := fmt.Sprintf(" cron %q", e.Schedule); len(line)+len(cron) <= handoffLineBytes {
			line += cron
		}
	case "instruction":
		line += fmt.Sprintf(" msg #%d by %s expires %s", e.Message, e.By, e.Expires)
	case "order":
		line += fmt.Sprintf(" %s rev %d order #%d next %s", e.Item, e.Revision, e.Order, e.Next)
	case "decision":
		line += fmt.Sprintf(" msg #%d authority %s", e.Message, e.By)
	case "claim":
		line += fmt.Sprintf(" msg #%d", e.Message)
		if e.Check > 0 {
			line += fmt.Sprintf(" check #%d", e.Check)
		}
	}
	return line
}

// handoffNoteLine is a body line and the note list it counts against when it
// is left out; headings and the snapshot lines count against none.
type handoffNoteLine struct {
	text, list string
}

// handoffBody is the note's body in its fixed order: active instructions,
// active wakes, open orders, the snapshot's counts, unverified claims,
// recorded decisions, then everything expired, revoked, cancelled or closed.
func handoffBody(r handoffRecord, now time.Time) []handoffNoteLine {
	var lines []handoffNoteLine
	group := func(heading string, k handoffKind, keep func(state string) bool) {
		first := true
		for _, e := range k.list(&r.Notes).Entries {
			if !keep(handoffEntryState(e, now)) {
				continue
			}
			if first {
				lines, first = append(lines, handoffNoteLine{heading, ""}), false
			}
			lines = append(lines, handoffNoteLine{handoffBriefLine(k, e, now), k.plural})
		}
	}
	kind := func(name string) handoffKind { k, _ := handoffKindNamed(name); return k }
	group("Active instructions:", kind("instruction"), handoffLive)
	group("Active wakes:", kind("wake"), handoffLive)
	group("Open orders:", kind("order"), handoffLive)
	if s := r.Snapshot; s != nil {
		lines = append(lines,
			handoffNoteLine{fmt.Sprintf("Hub snapshot as of %s (read the hub again before acting): helper %s", s.AsOf, s.HelperStatus), ""},
			handoffNoteLine{fmt.Sprintf("%d obligations, %d open owner decisions, %d queue entries launching or running",
				len(s.Obligations)+s.ObligationsOmitted, len(s.Decisions)+s.DecisionsOmitted, len(s.Queue)+s.QueueOmitted), ""},
			handoffNoteLine{handoffWindowText(s.Window), ""})
	}
	group("Unverified claims:", kind("claim"), handoffLive)
	group("Decisions taken:", kind("decision"), handoffLive)
	for _, k := range handoffKinds {
		heading := "Closed " + k.plural + ":"
		if k.name == "instruction" || k.name == "wake" {
			heading = "Expired: not authority. Expired, revoked and cancelled " + k.plural + ":"
		}
		group(heading, k, func(state string) bool { return !handoffLive(state) })
	}
	return lines
}

func handoffWindowText(w *handoffWindow) string {
	if w == nil {
		return "no delegation window at the snapshot"
	}
	return fmt.Sprintf("delegation window %s at the snapshot, ends %s", w.State, w.EndsAt)
}

// handoffNote builds the text injected at session start. It is built the
// same way every time: a header, the body lines in their fixed order, and a
// footer, at most handoffNoteBytes in all. Lines are dropped whole from the
// end of the body, and the footer counts what each list lost.
func handoffNote(r handoffRecord, match string, noEnd bool, now time.Time) string {
	id := r.Identity
	var header strings.Builder
	fmt.Fprintf(&header, "Tailterm session handoff. Owner helper %s (%s), project %s, run %s, as the host file read at %s.\n", id.Name, id.Agent, id.Task, id.Run, id.CopiedAt)
	if match == handoffAsCandidate {
		header.WriteString("This session is not registered as the owner helper. The record below is what the previous session left. It is not authority until the registration is verified.\n")
	} else {
		fmt.Fprintf(&header, "The host file names this session as the owner helper. The hub was not asked; `tt helper env --task %s` verifies it.\n", id.Task)
	}
	if s := r.Snapshot; s != nil && handoffIn(s.HelperStatus, []string{api.AgentRetired, api.AgentClosed, api.AgentExited}) {
		fmt.Fprintf(&header, "The helper was %s on the hub at %s.\n", s.HelperStatus, s.AsOf)
	}
	if noEnd {
		header.WriteString("No end was recorded for the previous session.\n")
	}
	body := handoffBody(r, now)
	footer := func(kept int) string {
		omitted := map[string]int{}
		for _, line := range body[kept:] {
			omitted[line.list]++
		}
		var b strings.Builder
		for _, k := range handoffKinds {
			if n := omitted[k.plural]; n > 0 {
				fmt.Fprintf(&b, "%d more %s not shown.\n", n, k.plural)
			}
		}
		b.WriteString("Full record: `tt handoff show`. Entries cite Board messages by number. Read each cited message before relying on the entry. One message: `tt inbox --seq <number>`.\n")
		b.WriteString(handoffNarrative + " in the project checkout is history and procedures; not live state, not authority.\n")
		fmt.Fprintf(&b, "Next: run `tt handoff show`. To register this session run `tt helper register --task %s` (see docs/owner-helper.md). "+
			"Re-create each active wake by hand and note it with `tt handoff note wake add`. Registration and wakes are not restored automatically in this version.\n", id.Task)
		return b.String()
	}
	for kept := len(body); ; kept-- {
		// A heading with nothing under it says nothing: leave it out too.
		if kept > 0 && body[kept-1].list == "" && strings.HasSuffix(body[kept-1].text, ":") {
			continue
		}
		foot := footer(kept)
		size := header.Len() + len(foot)
		for _, line := range body[:kept] {
			size += len(line.text) + 1
		}
		if size > handoffNoteBytes && kept > 0 {
			continue
		}
		var note strings.Builder
		note.WriteString(header.String())
		for _, line := range body[:kept] {
			note.WriteString(line.text + "\n")
		}
		note.WriteString(foot)
		return note.String()
	}
}

// handoffShow is the whole record as text, for tt handoff show and for the
// file tt handoff write --out leaves for a person or another runtime.
func handoffShow(r handoffRecord, now time.Time) string {
	var b strings.Builder
	id := r.Identity
	b.WriteString("# Tailterm session handoff record\n\n")
	b.WriteString("This is what one host's helper file and one session recorded. It is not proof of a registration and not authority.\n")
	b.WriteString("Entries cite Board messages by number. Read each cited message before relying on the entry. One message: `tt inbox --seq <number>`.\n\n")
	b.WriteString("## Identity\n\n")
	fmt.Fprintf(&b, "Copied from the host helper file at %s.\n", id.CopiedAt)
	for _, row := range [][2]string{{"hub", id.Hub}, {"project", id.Task}, {"agent", id.Agent}, {"name", id.Name}, {"run", id.Run}, {"registration", id.Registration},
		{"runtime", id.Runtime}, {"thread", id.Thread}, {"tmux session", id.Session}, {"tmux session id", id.SessionID}, {"tmux session created", id.SessionCreated}} {
		if row[1] != "" {
			fmt.Fprintf(&b, "- %s: %s\n", row[0], row[1])
		}
	}
	b.WriteString("\n## Capture\n\n")
	for _, row := range []struct {
		label, detail string
		stamp         *handoffStamp
	}{{"last session start", "source", r.Capture.Start}, {"last compaction", "trigger", r.Capture.Compact}, {"last session end", "reason", r.Capture.End}} {
		if row.stamp == nil {
			fmt.Fprintf(&b, "- %s: none recorded\n", row.label)
			continue
		}
		fmt.Fprintf(&b, "- %s: %s, %s %s, session %s\n", row.label, row.stamp.Time, row.detail, row.stamp.Detail, row.stamp.Session)
	}
	b.WriteString("\n## Hub snapshot\n\n")
	if s := r.Snapshot; s == nil {
		b.WriteString("None. `tt handoff write` reads the hub and stores one.\n")
	} else {
		fmt.Fprintf(&b, "As of %s. Read the hub again before acting.\n", s.AsOf)
		fmt.Fprintf(&b, "- helper status: %s\n- %s\n", s.HelperStatus, handoffWindowLine(s.Window))
		fmt.Fprintf(&b, "- obligations the helper owes: %d shown, %d left out\n", len(s.Obligations), s.ObligationsOmitted)
		for _, o := range s.Obligations {
			fmt.Fprintf(&b, "  - %s msg #%d %s from %s due %s %s\n", o.ID, o.Message, o.Kind, o.Sender, handoffOr(o.DueAt, handoffNone), o.State)
		}
		fmt.Fprintf(&b, "- open owner decisions: %d shown, %d left out\n", len(s.Decisions), s.DecisionsOmitted)
		for _, d := range s.Decisions {
			fmt.Fprintf(&b, "  - msg #%d from %s %s\n", d.Message, d.Sender, d.State)
		}
		fmt.Fprintf(&b, "- queue entries launching or running: %d shown, %d left out\n", len(s.Queue), s.QueueOmitted)
		for _, q := range s.Queue {
			fmt.Fprintf(&b, "  - %s %s rev %d order #%d %s\n", q.ID, q.Item, q.Revision, q.Order, q.State)
		}
	}
	b.WriteString("\n## Session notes\n")
	section := func(title string, k handoffKind, keep func(string) bool) {
		var lines []string
		for _, e := range k.list(&r.Notes).Entries {
			if keep(handoffEntryState(e, now)) {
				lines = append(lines, "- "+handoffEntryLine(k, e, now))
			}
		}
		if len(lines) > 0 {
			b.WriteString("\n" + title + "\n" + strings.Join(lines, "\n") + "\n")
		}
	}
	for _, k := range handoffKinds {
		section("Current "+k.plural+":", k, handoffLive)
	}
	for _, k := range handoffKinds {
		title := "Closed " + k.plural + ", kept for the record:"
		if k.name == "instruction" || k.name == "wake" {
			title = "Expired: not authority. Expired, revoked and cancelled " + k.plural + ":"
		}
		section(title, k, func(state string) bool { return !handoffLive(state) })
	}
	b.WriteString("\nLists:\n")
	for _, k := range handoffKinds {
		list := k.list(&r.Notes)
		fmt.Fprintf(&b, "- %s: %d entries, last changed %s, dropped %d\n", k.plural, len(list.Entries), handoffOr(list.Changed, "never"), list.Dropped)
	}
	return b.String()
}

func handoffWindowLine(w *handoffWindow) string {
	if w == nil {
		return "delegation window: none"
	}
	return fmt.Sprintf("delegation window: %s, scope %s, ends %s, %s", w.ID, w.Scope, w.EndsAt, w.State)
}

func handoffOr(value, empty string) string {
	if value == "" {
		return empty
	}
	return value
}

// ---- tt handoff ----

// handoffRoute is the command dispatch for tt handoff: the handler for the
// words that follow, and how many of them it consumed.
func handoffRoute(args []string) (func(e env, args []string) error, int) {
	if len(args) == 0 {
		return nil, 0
	}
	switch args[0] {
	case "show":
		return handoffShowCommand, 1
	case "write":
		return handoffWriteCommand, 1
	case "note":
		if len(args) < 3 {
			return nil, 0
		}
		k, ok := handoffKindNamed(args[1])
		if !ok || args[2] != "add" && args[2] != "set" && args[2] != "close" {
			return nil, 0
		}
		action := args[2]
		return func(e env, rest []string) error { return handoffNoteCommand(e, k, action, rest) }, 3
	}
	return nil, 0
}

func cmdHandoff(e env, args []string) error {
	run, used := handoffRoute(args)
	if run == nil {
		return errors.New(handoffUsage)
	}
	return run(e, args[used:])
}

func handoffFlags(name string) *flag.FlagSet {
	fs := flag.NewFlagSet(name, flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	return fs
}

// handoffHelperFor finds the helper file a command acts on: the project's
// when --task names one, otherwise the one registered from this runtime
// session. It asks no hub.
func handoffHelperFor(e env, task string) (ownerHelperFile, error) {
	files, _ := handoffHelperFiles()
	runtime, thread, single := sessionHelperThread()
	if task == "" {
		if f, ok := handoffMatchThread(files, runtime, thread); ok && single {
			return f, nil
		}
		return ownerHelperFile{}, errors.New("this session is not a registered owner helper on this host; name the project with --task")
	}
	if !api.ValidID(task, "tsk") {
		return ownerHelperFile{}, errors.New("--task is not a project id")
	}
	var found []ownerHelperFile
	for _, f := range files {
		if f.Task == task && (e.hub == "" || f.Hub == e.hub) {
			found = append(found, f)
		}
	}
	if len(found) != 1 {
		return ownerHelperFile{}, errors.New("no owner helper is registered on this host for this project; run tt helper register")
	}
	return found[0], nil
}

// handoffWriter is the helper a command may write notes for. A runtime
// session other than the registered one is refused, and so is an agent
// identity that is not the helper's. A shell with no runtime session is the
// owner typing by hand and is allowed.
func handoffWriter(e env, task string) (ownerHelperFile, error) {
	helper, err := handoffHelperFor(e, task)
	if err != nil {
		return ownerHelperFile{}, err
	}
	runtime, thread, single := sessionHelperThread()
	both := !single && os.Getenv("CODEX_THREAD_ID") != ""
	if both || single && (runtime != helper.Runtime || thread != helper.Thread) || e.agent != "" && e.agent != helper.Agent {
		return ownerHelperFile{}, errors.New("this session is not the registered owner helper; run tt helper register first")
	}
	return helper, nil
}

func handoffNoteCommand(e env, k handoffKind, action string, args []string) error {
	if !handoffOn() {
		return handoffOffError()
	}
	id := ""
	if action != "add" {
		if len(args) == 0 || !handoffEntryIDPattern.MatchString(args[0]) || !strings.HasPrefix(args[0], k.prefix) {
			return fmt.Errorf("name the %s by its id, such as %s1", k.name, k.prefix)
		}
		id, args = args[0], args[1:]
	}
	fs := handoffFlags("handoff note")
	task := fs.String("task", e.task, "project id")
	fields := append([]string{}, k.fields...)
	if action == "close" {
		fields = []string{"state"}
		if k.checkOnClose {
			fields = append(fields, "check")
		}
	}
	values := map[string]*string{}
	for _, field := range fields {
		values[field] = fs.String(field, "", "")
	}
	if err := fs.Parse(args); err != nil || fs.NArg() > 0 {
		return errors.New(handoffUsage)
	}
	given := map[string]bool{}
	fs.Visit(func(f *flag.Flag) { given[f.Name] = true })
	helper, err := handoffWriter(e, *task)
	if err != nil {
		return err
	}
	store, ok := handoffStoreFor(helper.Agent, handoffCommandLockWait)
	if !ok {
		return errors.New("no handoff state directory")
	}
	now := handoffNow()
	stamp := handoffStamped(now)
	// The entry is built and validated in full before the directory, the lock
	// or the record is touched, so a refused value changes nothing.
	change := handoffEntry{}
	for _, field := range fields {
		if !given[field] || field == "state" {
			continue
		}
		if err := handoffSetField(k, &change, field, *values[field]); err != nil {
			return err
		}
	}
	state := ""
	switch action {
	case "add":
		for _, field := range k.required {
			if !given[field] {
				return fmt.Errorf("a %s note needs --%s", k.name, field)
			}
		}
	case "close":
		state = k.closed[0]
		if given["state"] {
			state = *values["state"]
		} else if len(k.closed) > 1 && k.checkOnClose {
			return fmt.Errorf("closing a %s needs --state %s", k.name, strings.Join(k.closed, "|"))
		}
		if !handoffIn(state, k.closed) {
			return fmt.Errorf("--state is not one of: %s", strings.Join(k.closed, ", "))
		}
		if k.checkOnClose && !given["check"] {
			return fmt.Errorf("closing a %s needs --check with the Board message number of the check", k.name)
		}
	default:
		if len(given) == 0 || len(given) == 1 && given["task"] {
			return errors.New("nothing to set")
		}
	}
	if err := store.prepare(); err != nil {
		return err
	}
	unlock := store.lock()
	if unlock == nil {
		return errors.New("the handoff record is locked by another command; try again")
	}
	defer unlock()
	r, previous, err := store.load()
	if errors.Is(err, errHandoffNoRecord) {
		r, err = handoffRecord{V: 1}, nil
	}
	if err != nil {
		return err
	}
	r.refreshIdentity(helper)
	list := k.list(&r.Notes)
	var entry handoffEntry
	if action == "add" {
		if len(list.Entries) >= handoffListCap {
			// Make room by dropping the oldest entry that is no longer
			// current. Current entries are never dropped.
			oldest := -1
			for i, e := range list.Entries {
				if !handoffLive(handoffEntryState(e, now)) {
					oldest = i
					break
				}
			}
			if oldest < 0 {
				return fmt.Errorf("the %s list is full (%d current entries); close one first", k.plural, handoffListCap)
			}
			list.Entries = append(list.Entries[:oldest:oldest], list.Entries[oldest+1:]...)
			list.Dropped++
		}
		list.Next = max(list.Next, 1)
		entry = change
		entry.ID, entry.State, entry.Created, entry.Updated = k.prefix+strconv.Itoa(list.Next), k.open, stamp, stamp
		if handoffIn("expires", k.fields) && entry.Expires == "" {
			entry.Expires = handoffNone
		}
		if handoffIn("given", k.fields) && entry.Given == "" {
			entry.Given = stamp
		}
		list.Next++
		list.Entries = append(list.Entries, entry)
	} else {
		at := -1
		for i, e := range list.Entries {
			if e.ID == id {
				at = i
			}
		}
		if at < 0 {
			return fmt.Errorf("no %s %s in the record", k.name, id)
		}
		entry = list.Entries[at]
		for _, field := range fields {
			if given[field] && field != "state" {
				_ = handoffSetField(k, &entry, field, *values[field]) // validated above
			}
		}
		if action == "close" {
			entry.State = state
		}
		entry.Updated = stamp
		list.Entries[at] = entry
	}
	list.Changed = stamp
	if err := store.save(r, previous); err != nil {
		return err
	}
	fmt.Println(handoffEntryLine(k, entry, now))
	return nil
}

func handoffShowCommand(e env, args []string) error {
	fs := handoffFlags("handoff show")
	task := fs.String("task", e.task, "project id")
	asJSON := fs.Bool("json", false, "print the record as JSON")
	if err := fs.Parse(args); err != nil || fs.NArg() > 0 {
		return errors.New(handoffUsage)
	}
	agent, err := handoffShowAgent(e, *task)
	if err != nil {
		return err
	}
	store, ok := handoffStoreFor(agent, handoffCommandLockWait)
	if !ok {
		return errors.New("no handoff state directory")
	}
	r, _, err := store.load()
	if errors.Is(err, errHandoffNoRecord) {
		return fmt.Errorf("no handoff record for %s on this host", agent)
	}
	if err != nil {
		return err
	}
	now := handoffNow()
	if *asJSON {
		// The stored states, with expiry applied as of now, as the text shows.
		for _, k := range handoffKinds {
			list := k.list(&r.Notes)
			for i := range list.Entries {
				list.Entries[i].State = handoffEntryState(list.Entries[i], now)
			}
		}
		printJSON(r)
		return nil
	}
	fmt.Print(handoffShow(r, now))
	if !handoffOn() {
		fmt.Printf("\nSession handoff is off on this host (%s). The record is kept and shown; nothing updates it.\n", handoffConfigPath())
	}
	return nil
}

// handoffShowAgent finds whose record to show without the hub: the named
// project's helper, the helper registered from this session, the helper
// whose tmux session this is, or the only record on the host.
func handoffShowAgent(e env, task string) (string, error) {
	if helper, err := handoffHelperFor(e, task); err == nil {
		return helper.Agent, nil
	} else if task != "" {
		return "", err
	}
	files, _ := handoffHelperFiles()
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	if helper, ok := handoffMatchTmux(ctx, files); ok {
		return helper.Agent, nil
	}
	root := handoffRoot()
	handoffTouch(root)
	entries, _ := os.ReadDir(root)
	var agents []string
	for _, entry := range entries {
		if entry.IsDir() && api.ValidID(entry.Name(), "agt") {
			agents = append(agents, entry.Name())
		}
	}
	if len(agents) == 1 {
		return agents[0], nil
	}
	return "", errors.New("cannot tell which handoff record this session means; name the project with --task")
}

// handoffWriteCommand reads the hub for the snapshot and rewrites the record.
// It reads the helper agent, its delegation windows, the obligations it owes
// (and, for who sent each, its one Board message), the open owner decisions
// and the team queue. It reads no work-item record
// and changes nothing on the hub: the obligations are listed without a run,
// so none is marked delivered.
func handoffWriteCommand(e env, args []string) error {
	fs := handoffFlags("handoff write")
	task := fs.String("task", e.task, "project id")
	out := fs.String("out", "", "also render the record to this file")
	if err := fs.Parse(args); err != nil || fs.NArg() > 0 {
		return errors.New(handoffUsage)
	}
	if !handoffOn() {
		return handoffOffError()
	}
	if *task == "" {
		return errors.New(handoffUsage)
	}
	helper, err := handoffWriter(e, *task)
	if err != nil {
		return err
	}
	if e.hub == "" {
		e.hub = helper.Hub
	}
	if e.hub != helper.Hub {
		return errors.New("the owner helper on this host is registered with another hub")
	}
	snapshot, err := handoffReadHub(e, helper)
	if err != nil {
		return err
	}
	store, ok := handoffStoreFor(helper.Agent, handoffCommandLockWait)
	if !ok {
		return errors.New("no handoff state directory")
	}
	if err := store.prepare(); err != nil {
		return err
	}
	unlock := store.lock()
	if unlock == nil {
		return errors.New("the handoff record is locked by another command; try again")
	}
	defer unlock()
	r, previous, err := store.load()
	if errors.Is(err, errHandoffNoRecord) {
		r, err = handoffRecord{V: 1}, nil
	}
	if err != nil {
		return err
	}
	r.refreshIdentity(helper)
	r.Snapshot = &snapshot
	if err := store.save(r, previous); err != nil {
		return err
	}
	path := store.path("record.json")
	size := int64(0)
	if info, err := os.Stat(path); err == nil {
		size = info.Size()
	}
	fmt.Printf("handoff record written: %s (%d bytes), hub snapshot as of %s\n", path, size, snapshot.AsOf)
	destination := fmt.Sprintf("In the destination session, in its own one-pane tmux session:\n  tt helper register --task %[1]s\n  tt handoff show --task %[1]s\n  tt handoff note wake add ...   (after re-creating each active wake by hand)\n", helper.Task)
	if *out != "" {
		text := handoffShow(r, handoffNow()) + "\n## For the destination session\n\n" + destination +
			"Registration and wakes are not restored automatically in this version. This file is a copy; the record and the hub are the sources.\n"
		handoffTouch(*out)
		if err := os.WriteFile(*out, []byte(text), 0600); err != nil {
			return err
		}
		fmt.Printf("rendered: %s\n", *out)
	}
	fmt.Print(destination)
	return nil
}

func handoffReadHub(e env, helper ownerHelperFile) (handoffSnapshot, error) {
	c, err := e.client(10 * time.Second)
	if err != nil {
		return handoffSnapshot{}, err
	}
	ctx, cancel := ctxTimeout(30 * time.Second)
	defer cancel()
	a, err := c.GetAgent(ctx, helper.Task, helper.Agent)
	if err != nil {
		return handoffSnapshot{}, err
	}
	if a.Role != api.AgentRoleOwnerHelper || a.RunID != helper.Run {
		return handoffSnapshot{}, errors.New("the owner helper was registered again elsewhere; run tt helper register here first")
	}
	now := handoffNow()
	s := handoffSnapshot{AsOf: handoffStamped(now), HelperStatus: handoffListed(a.Status, handoffAgentStatuses),
		Obligations: []handoffObligation{}, Decisions: []handoffDecision{}, Queue: []handoffQueueRow{}}
	sender := func(from api.Sender) string {
		switch {
		case api.ValidID(from.AgentID, "agt"):
			return from.AgentID
		case from.AgentID == "" && from.User != "":
			return "human"
		}
		return "unknown"
	}
	windows, err := c.ListDelegationWindows(ctx, helper.Task)
	if err != nil {
		return handoffSnapshot{}, err
	}
	// The helper's newest window: an open one if there is one.
	var window *api.DelegationWindow
	for i, w := range windows.Windows {
		if w.DelegateAgentID != helper.Agent || !handoffID(w.ID, "dlw") {
			continue
		}
		if window == nil || w.Active(now) && !window.Active(now) || w.Active(now) == window.Active(now) && w.CreatedAt.After(window.CreatedAt) {
			window = &windows.Windows[i]
		}
	}
	if window != nil {
		state := handoffListed(window.State, handoffWindowStates)
		if state == handoffOther || state == api.DelegationOpen && !now.Before(window.EndsAt) {
			state = api.DelegationExpired
		}
		s.Window = &handoffWindow{ID: window.ID, Scope: handoffListed(window.Scope, handoffWindowScopes), EndsAt: handoffStamped(window.EndsAt), State: state}
	}
	obligations, err := c.ListObligations(ctx, helper.Task, helper.Agent, "", true, false)
	if err != nil {
		return handoffSnapshot{}, err
	}
	for _, o := range obligations {
		if o.AgentID != helper.Agent || !handoffID(o.ID, "obl") || o.MessageSeq < 1 {
			continue
		}
		if len(s.Obligations) == handoffListCap {
			s.ObligationsOmitted++
			continue
		}
		row := handoffObligation{ID: o.ID, Message: o.MessageSeq, Kind: handoffListed(o.SourceKind, handoffObligKinds), Sender: "unknown", State: handoffListed(o.State, handoffObligStates)}
		if o.Request != nil {
			row.Sender = sender(o.Request.From)
		} else if page, err := c.ListMessages(ctx, helper.Task, o.MessageSeq-1, "", 1); err == nil && len(page) == 1 && page[0].Seq == o.MessageSeq {
			// The listing carries the request only for the owner's own
			// obligations; read the one message for who sent it. Its text
			// is not kept.
			row.Sender = sender(page[0].From)
		}
		if !o.DueAt.IsZero() {
			row.DueAt = handoffStamped(o.DueAt)
		}
		s.Obligations = append(s.Obligations, row)
	}
	for after, pages := int64(0), 0; pages < 200; pages++ {
		page, err := c.ListDecisions(ctx, helper.Task, after, api.MaxDecisionPage)
		if err != nil {
			return handoffSnapshot{}, err
		}
		for _, d := range page.Decisions {
			if d.Answer != nil || d.Request.Seq < 1 {
				continue
			}
			if len(s.Decisions) == handoffListCap {
				s.DecisionsOmitted++
				continue
			}
			s.Decisions = append(s.Decisions, handoffDecision{Message: d.Request.Seq, Sender: sender(d.Request.From), State: "open"})
		}
		if page.NextAfter <= after {
			break
		}
		after = page.NextAfter
	}
	queue, err := c.ListTeamQueuePage(ctx, helper.Task, api.TeamQueueListOptions{View: api.TeamQueueViewActive})
	if err != nil {
		return handoffSnapshot{}, err
	}
	for _, q := range queue.Entries {
		if !handoffIn(q.State, handoffQueueStates) || !handoffID(q.ID, "tqe") || !api.ValidID(q.ItemID, "wi") || q.ItemRevision < 1 {
			continue
		}
		if len(s.Queue) == handoffListCap {
			s.QueueOmitted++
			continue
		}
		s.Queue = append(s.Queue, handoffQueueRow{ID: q.ID, Item: q.ItemID, Revision: q.ItemRevision, Order: q.OrderMessageSeq, State: q.State})
	}
	return s, nil
}
